#!/usr/bin/python3

l7_categories = {
    "Business",
    "Conferencing",
    "Email",
    "File sharing P2P",
    "File storage and backup",
    "Games",
    "Instant messaging",
    "Media streaming",
    "Mobile",
    "Proxies and anonymizers",
    "Remote access",
    "Social networking",
    "Standard networks",
    "Trojan Horses",
    "Tunneling",
    "VOIP",
    "Web browsing",
    "Web posting",
}

cp_app_category = {
    "Anonymizer": {"type": "l7_category", "name": ["Proxies and anonymizers"]},
    "Alcohol & Tobacco": {"type": "url_category", "name": ["Alcohol & Tobacco"]},
#    "Artificial Intelligence (AI)": None,   # {"type": "url_category", "name": ["Chat-bot AI"]}
    "Blogs / Personal Pages": {"type": "url_category", "name": ["Personal Sites"]},
    "Botnets": {"type": "url_category", "name": ["Botnets"]},
#    "Browser Plugin": None,
#    "Browser Toolbar": None,
    "Business / Economy": {"type": "l7_category", "name": ["Business"]},
#    "Check Point Products": None,
    "Child Abuse": {"type": "url_category", "name": ["Child Abuse Images"]},
    "Cloud Services": {"type": "applicationgroup", "name": ["Cloud Services"]},     # Новая категория
    "Computers / Internet": {"type": "l7_category", "name": ["Standard networks"]},
    "Critical Risk": {"type": "url_category", "name": ["Reputation: High risk"]},
    "Cryptocurrency": {"type": "url_category", "name": ["Cryptocurrency Mining"]},
    "Download Manager": {"type": "applicationgroup", "name": ["Download Manager"]}, # Новая категория
    "Education": {"type": "url_category", "name": ["Education"]},
    "Email": {"type": "l7_category", "name": ["Email"]},
    "Encrypts communications": {"type": "l7_category", "name": ["Tunneling", "Proxies and anonymizer"]},
    "Entertainment": {"type": "url_category", "name": ["Entertainment"]},
    "Fashion": {"type": "url_category", "name": ["Fashion & Beauty"]},
#    "Facebook Business": None,
#    "Facebook Education": None,
#    "Facebook Entertainment": None,
#    "Facebook Friends & Family": None,
#    "Facebook Games": None,
#    "Facebook Lifestyle": None,
#    "Facebook Sports": None,
#    "Facebook Utilities": None,
#    "Facebook Widgets": None,
    "File Storage and Sharing": {"type": "l7_category", "name": ["File storage and backup"]},
    "File Upload": {"type": "applicationgroup", "name": ["File Upload"]},          # Новая категория
    "Financial Services": {"type": "url_category", "name": ["Finance"]},
#    "Friendster Widgets": None,
    "Gambling": {"type": "url_category", "name": ["Gambling"]},
    "Games": {"type": "l7_category", "name": ["Games"]},
#    "Google Plus Widgets": None,
    "Government / Military": {"type": "url_category", "name": ["Government", "Military"]},
    "High Risk": {"type": "url_category", "name": ["Reputation: High risk"]},
    "Hacking": {"type": "url_category", "name": ["Hacking"]},
    "Hate / Racism": {"type": "url_category", "name": ["Hate & Intolerance"]},
    "Health": {"type": "url_category", "name": ["Health & Medicine"]},
    "High Bandwidth": {"type": "l7_category", "name": ["Proxies and anonymizer", "File sharing P2P", "File storage and backup"]},
    "Illegal / Questionable": {"type": "url_category", "name": ["Tasteless", "Violence", "Criminal Activity", "Hate & Intolerance", "Profanity"]},
    "Illegal Drugs": {"type": "url_category", "name": ["Illegal Drug"]},
    "Inactive Sites": {"type": "url_category", "name": ["Parked Domains", "General"]},
    "Instant Chat": {"type": "applicationgroup", "name": ["Instant Chat"]},        # Новая категория
    "Instant Messaging": {"type": "l7_category", "name": ["Instant messaging"]},
#    "IPTV": None,
    "Job Search / Careers": {"type": "url_category", "name": ["Job Search"]},
    "Lingerie and Swimsuit / Suggestive": {"type": "url_category", "name": ["Nudity"]},
#    "LinkedIn Widgets": None,
    "Marijuana": {"type": "url_category", "name": ["Illegal Drug"]},
    "Media Sharing": {"type": "applicationgroup", "name": ["Media Sharing"]},      # Новая категория
    "Media Streams": {"type": "l7_category", "name": ["Media streaming"]},
    "Medium Risk": {"type": "url_category", "name": ["Reputation: Medium risk"]},
    "Microsoft & Office365 Services": {"type": "applicationgroup", "name": ["Microsoft and Office365 Services"]}, # Новая категория
    "Mobile Software": {"type": "l7_category", "name": ["Mobile"]},
#    "MySpace Widgets": None,
    "Network Protocols": {"type": "l7_category", "name": ["Standard networks"]},
    "Network Utilities": {"type": "l7_category", "name": ["Standard networks"]},
    "News / Media": {"type": "url_category", "name": ["News"]},
    "Newsgroups / Forums": {"type": "url_category", "name": ["Forums & Newsgroups"]},
#    "Ning.com Widgets": None,
    "Nudity": {"type": "url_category", "name": ["Nudity"]},
    "P2P File Sharing": {"type": "l7_category", "name": ["File sharing P2P"]},
    "Personals / Dating": {"type": "url_category", "name": ["Dating & Personals"]},
    "Phishing": {"type": "url_category", "name": ["Phishing & Fraud"]},
    "Political / Legal": {"type": "url_category", "name": ["Legal", "Politics"]},
    "Pornography": {"type": "url_category", "name": ["Pornography/Sexually Explicit"]},
    "Real Estate": {"type": "url_category", "name": ["Real Estate"]},
    "Remote Administration": {"type": "l7_category", "name": ["Remote access"]},
    "Restaurants / Dining / Foods": {"type": "url_category", "name": ["Restaurants & Dining"]},
    "Religion": {"type": "url_category", "name": ["Religion"]},
#    "SCADA Protocols": None,
    "Sex": {"type": "url_category", "name": ["Gay, Lesbian or Bisexual", "Nudity", "Pornography/Sexually Explicit"]},
    "Sex Education": {"type": "url_category", "name": ["Sex Education"]},
    "Search Engines / Portals": {"type": "url_category", "name": ["Search Engines & Portals"]},
    "Shopping": {"type": "url_category", "name": ["Shopping"]},
#    "SMS Tools": None,
    "Social Networking": {"type": "l7_category", "name": ["Social networking"]},
#    "Social Plugins": None,
    "Software Downloads": {"type": "url_category", "name": ["Download Sites"]},
    "Software Update": {"type": "l7_category", "name": ["Software update"]},
    "Spam": {"type": "url_category", "name": ["Spam Sites"]},
    "Sports": {"type": "url_category", "name": ["Sports"]},
    "Spyware / Malicious Sites": {"type": "url_category", "name": ["Compromised", "Phishing & Fraud", "Malware"]},
    "Stealth Tactics": {"type": "url_category", "name": ["Malware"]},
    "Suspicious Content": {"type": "url_category", "name": ["Tasteless", "Phishing & Fraud", "Compromised", "Spam Sites", "Malware"]},
    "Tasteless": {"type": "url_category", "name": ["Tasteless"]},
    "Translation": {"type": "url_category", "name": ["Translators"]},
    "Travel": {"type": "url_category", "name": ["Travel"]},
#    "Twitter Clients": None,
    "Vehicles": {"type": "url_category", "name": ["Transportation"]},
    "Video Conferencing": {"type": "l7_category", "name": ["Conferencing"]},
    "Violence": {"type": "url_category", "name": ["Violence"]},
    "VoIP": {"type": "l7_category", "name": ["VOIP"]},
    "Weapons": {"type": "url_category", "name": ["Weapons"]},
#    "Web Advertisements": None,
#    "Web Browser": None,
#    "Web Browser Acceleration": None,
    "Web Conferencing": {"type": "l7_category", "name": ["Conferencing"]},
#    "Web Content Aggregators": None,
    "Web Services Provider": {"type": "l7_category", "name": ["Web browsing"]},
#    "Web Spider": None,
}

url_categories = {
    "Advertisements & Pop-Ups": 1,                      # Реклама и всплывающие окна
    "Alcohol & Tobacco": 2,                             # Алкоголь и табак
    "Anonymizers": 3,                                   # Анонимайзеры
    "Arts": 4,                                          # Искусство
    "Botnets": 61,                                      # Ботнеты
    "Business": 5,                                      # Бизнес
    "CDNs": 58,                                         # CDN
    "Chat": 7,                                          # Чаты
    "Chat-bot AI": 85,                                  # Чат-боты искусственного интеллекта
    "Child Abuse Images": 78,                           # Изображения жестокого обращения с детьми
    "Compromised": 10,                                  # Заражённые сайты
    "Computers & Technology": 11,                       # Компьютеры и технологии
    "Criminal Activity": 12,                            # Преступная деятельность
    "Cryptocurrency Mining": 66,                        # Криптомайнеры
    "Cults": 62,                                        # Регилиозные культы
    "Dating & Personals": 13,                           # Сайты знакомств
    "Download Sites": 14,                               # Douwload-архивы
    "Education": 15,                                    # Образование
    "Entertainment": 16,                                # Развлечения
    "Fashion & Beauty": 63,                             # Мода и красота
    "Finance": 17,                                      # Финансы
    "Forums & Newsgroups": 9,                           # Форумы и новостные ленты
    "Gambling": 18,                                     # Азартные игры
    "Games": 19,                                        # Игры
    "Gay, Lesbian or Bisexual": 79,                     # Нетрадиционная сексуальная ориентация
    "General": 49,                                      # Общие
    "Government": 20,                                   # Правительство
    "Greeting cards": 64,                               # Поздравительные открытки
    "Hacking": 65,                                      # Хакерство
    "Hate & Intolerance": 21,                           # Ненависть и нетерпимость
    "Health & Medicine": 22,                            # Здоровье и медицина
    "Illegal Drug": 23,                                 # Наркотики
    "Illegal Software": 67,                             # Нелегальное ПО
    "Image Sharing": 68,                                # Обмен картинками
    "Information Security": 69,                         # Информационная безопасность
    "Instant Messaging": 70,                            # Сервисы мгновенных сообщений
    "Job Search": 24,                                   # Поиск работы
    "Kids sites": 8,                                    # Детские сайты
    "Legal": 52,                                        # Юриспруденция
    "Leisure & Recreation": 50,                         # Отдых и оздоровление
    "Literature & Books": 80,                           # Литература и книги
    "Local Information": 53,                            # Местные достопримечательность
    "Malware": 42,                                      # Вредоносное ПО
    "Military": 25,                                     # Военные сайты
    "Network Errors": 71,                               # Сетевые ошибки
    "News": 27,                                         # Новости
    "Non-profits & NGOs": 28,                           # Некоммерческие и неправительственные организации
    "Nudity": 29,                                       # Нудизм
    "Nutrition & Diet": 81,                             # Здоровое питание и диеты
    "Online training and tools": 51,                    # Онлайн обучение
    "Parked Domains": 72,                               # Паркованные домены
    "Peer-to-Peer": 73,                                 # Пиринговые сети
    "Personal Sites": 30,                               # Персональные сайты
    "Personal Storage": 57,                             # Персональные хранилища
    "Pets & Animals": 82,                               # Домашние животные
    "Phishing & Fraud": 31,                             # Фишинг и мошенничество
    "Politics": 32,                                     # Политика
    "Pornography/Sexually Explicit": 33,                # Порнография и насилие
    "Private IP Addresses": 74,                         # Частные IP-адреса
    "Profanity": 59,                                    # Нецензурная лексика
    "Professional social networks": 60,                 # Профессиональные социальные сети
    "Real Estate": 34,                                  # Недвижимость
    "Reference and Research": 54,                       # Справочная информация
    "Religion": 35,                                     # Религия
    "Reputation: Low risk": 97,
    "Reputation: Medium risk": 98,
    "Reputation: High risk": 99,
    "Restaurants & Dining": 36,                         # Рестораны и еда
    "School Cheating": 75,                              # Школьные мошенничества
    "Search Engines & Portals": 37,                     # Поисковые системы и порталы
    "Sex Education": 76,                                # Половое воспитание
    "Shopping": 38,                                     # Покупки
    "Social Networking": 39,                            # Социальные сети
    "Spam Sites": 40,                                   # Спам-сайты
    "Sports": 41,                                       # Спорт
    "Stock trading": 43,                                # Фондовый рынок
    "Streaming Media & Downloads": 26,                  # Потоковое мультимедиа и загрузки
    "Tasteless": 77,                                    # Сайты сомнительного содержания - ?
    "Technical or business forums and news groups": 55, # Форумы с технической или бизнес информацией
    "Technical information and documentation": 56,      # Техническая информация
    "Translators": 44,                                  # Переводчики
    "Transportation": 6,                                # Транспорт
    "Travel": 45,                                       # Путешествия
    "Violence": 46,                                     # Насилие
    "Unknown": 0,                                       # Неизвестная тематика
    "Updates": 84,                                      # Обновления
    "Weapons": 47,                                      # Оружие
    "Web-based Email": 48,                              # Веб-почта
}

cp_app_site = {
    "1C Enterprise": {
        "type": "l7apps",
        "name": ["1C", "1C-Connect", "1C-Connect audio", "1C-Connect chat",
                 "1C-Connect file transfer", "1C-Connect proxy", "1C-Connect remote access"]
    },
    "3DNews - Daily Digital Digest": {"type": "l7apps", "name": ["3DNews"]},
    "4chan & /b/": {"type": "l7apps", "name": ["4chan"]},
    "4shared": {"type": "l7apps", "name": ["4Shared"]},
    "4shared-download": {"type": "l7apps", "name": ["4Shared"]},
    "4shared-upload": {"type": "l7apps", "name": ["4Shared"]},
    "8Tracks": {"type": "l7apps", "name": ["8tracks"]},
    "ABS-CBN": {"type": "l7apps", "name": ["ABS-CBN"]},
    "Absolute Manage": {"type": "l7apps", "name": ["Absolute Manage"]},
    "Academia.edu": {"type": "l7apps", "name": ["ACADEMIA"]},
    "Acronis Snap Deploy": {"type": "l7apps", "name": ["Acronis"]},
    "Acronis TrueImage": {"type": "l7apps", "name": ["Acronis"]},
    "Adobe Connect": {"type": "l7apps", "name": ["Adobe"]},
    "Adobe Connect-meeting": {"type": "l7apps", "name": ["Adobe"]},
    "Adobe Connect-meeting-file sharing": {"type": "l7apps", "name": ["Adobe"]},
    "Adobe Connect-meeting-remote control": {"type": "l7apps", "name": ["Adobe"]},
    "Adobe Connect-meeting-screen sharing": {"type": "l7apps", "name": ["Adobe"]},
    "Adobe Creative Cloud": {"type": "l7apps", "name": ["Adobe"]},
    "Adobe Document Cloud": {"type": "l7apps", "name": ["Adobe"]},
    "Adobe Update": {"type": "l7apps", "name": ["Adobe Update"]},
    "ADrive": {"type": "l7apps", "name": ["Adrive"]},
    "AeroAdmin": {"type": "l7apps", "name": ["Aeroadmin"]},
    "Afaria": {"type": "l7apps", "name": ["Afaria"]},
    "Agoda": {"type": "l7apps", "name": ["Agoda"]},
    "AIM": {"type": "l7apps", "name": ["AIM"]},
    "AIM Express": {"type": "l7apps", "name": ["AIM"]},
    "AIM-audio chat": {"type": "l7apps", "name": ["AIM"]},
    "AIM-video chat": {"type": "l7apps", "name": ["AIM"]},
    "Airbnb": {"type": "l7apps", "name": ["AirBNB"]},
    "AirDroid": {"type": "l7apps", "name": ["AirDroid"]},
    "Alibaba": {"type": "l7apps", "name": ["Alibaba"]},
    "AliExpress": {"type": "l7apps", "name": ["AliExpress"]},
    "Alpemix": {"type": "l7apps", "name": ["Alpemix"]},
    "Altiris": {"type": "l7apps", "name": ["Altiris"]},
    "Ammy Admin": {"type": "l7apps", "name": ["Ammy Admin"]},
    "Anatomic P2P": {"type": "l7apps", "name": ["BitTorrent ammounce"]},
    "Ants P2P": {"type": "l7apps", "name": ["ANts P2P"]},
    "Arctic Torrent": {"type": "l7apps", "name": ["BitTorrent", "BitTorrent ammounce", "BitTorrent Scrape"]},
    "Amazon": {"type": "l7apps", "name": ["Amazon"]},
    "Amazon Chime": {"type": "l7apps", "name": ["Amazon Chime"]},
    "Amazon Prime Video": {"type": "l7apps", "name": ["AmazonPrimeVideo"]},
    "Amazon S3": {"type": "l7apps", "name": ["Amazon"]},
    "Amazon Web Services (AWS)": {"type": "l7apps", "name": ["Amazon"]},
    "American Airlines": {"type": "l7apps", "name": ["American Airlines"]},
    "American Express": {"type": "l7apps", "name": ["American Express"]},
    "Ammyy Admin": {"type": "l7apps", "name": ["Ammyy Admin"]},
    "aNobii": {"type": "l7apps", "name": ["aNobii"]},
    "Anonymox": {"type": "l7apps", "name": ["Anonymox"]},
    "Anonymizer/proxy avoidance sites": {"type": "url_category", "name": ["Anonymizers"]},
    "Anonytun VPN": {"type": "l7apps", "name": ["AnonyTun"]},
    "Ants P2P": {"type": "l7apps", "name": ["ANts P2P"]},
    "Any.do": {"type": "l7apps", "name": ["Any.do"]},
    "AnyDesk": {"type": "l7apps", "name": ["AnyDesk"]},
    "Anyplace Control": {"type": "l7apps", "name": ["Anyplace Control"]},
    "AOL Mail": {"type": "l7apps", "name": ["AOL Mail"]},
    "Apache Kafka": {"type": "l7apps", "name": ["Apache Kafka"]},
    "Apple AirPlay": {"type": "l7apps", "name": ["Apple AirPlay"]},
    "Apple Daily-video": {"type": "l7apps", "name": ["Apple Daily"]},
    "Apt-get": {"type": "l7_category", "name": ["Software update"]},
    "Apptivo CRM": {"type": "l7apps", "name": ["Apptivo CRM"]},
    "ARCserve Backup": {"type": "l7apps", "name": ["Arcserve"]},
    "Ares": {"type": "l7apps", "name": ["Ares"]},
    "Asana": {"type": "l7apps", "name": ["Asana"]},
    "aSmallWorld": {"type": "l7apps", "name": ["ASmallWorld"]},
    "Assistant": {"type": "l7apps", "name": ["Assistant"]},
    "Atlassian": {"type": "l7apps", "name": ["Atlassian"]},
    "EMC Avamar": {"type": "l7apps", "name": ["Avamar"]},
    "avast! Antivirus": {"type": "l7apps", "name": ["Avast"]},
    "avast! Antivirus-update": {"type": "l7apps", "name": ["Avast Update"]},
    "Avira Phantom VPN": {"type": "l7apps", "name": ["Avira Phantom"]},
    "Avira Antivir-update": {"type": "l7apps", "name": ["Avira Update"]},
    "AxiFile": {"type": "l7apps", "name": ["AxiFile"]},
    "BACHNet Protocol (Building Automation and Control Networks)": {"type": "l7apps", "name": ["BACnet"]},
    "Badongo": {"type": "l7apps", "name": ["Badongo"]},
    "Badoo": {"type": "l7apps", "name": ["Badoo"]},
    "Baidu Hi": {"type": "l7apps", "name": ["Baidu Hi"]},
    "Baidu Hi-video chat": {"type": "l7apps", "name": ["Baidu Hi"]},
    "Baidu Video Search": {"type": "l7apps", "name": ["Baidu Player"]},
    "Bandcamp": {"type": "l7apps", "name": ["Bandcamp"]},
    "Baofeng": {"type": "l7apps", "name": ["BAOFENG"]},
    "Basecamp": {"type": "l7apps", "name": ["Basecamp"]},
    "Battle.Net": {"type": "l7apps", "name": ["Battle.net"]},
    "BBC": {"type": "l7apps", "name": ["BBC"]},
    "bet365": {"type": "l7apps", "name": ["Bet365"]},
    "BGP Protocol": {"type": "l7apps", "name": ["BGP (Border Gateway Protocol)"]},
    "Bing": {"type": "l7apps", "name": ["Bing"]},
    "Bitbucket": {"type": "l7apps", "name": ["Bitbucket"]},
    "Bitbucket-download": {"type": "l7apps", "name": ["Bitbucket"]},
    "Bitbucket-upload": {"type": "l7apps", "name": ["Bitbucket"]},
    "Bitcasa": {"type": "l7apps", "name": ["Bitcasa"]},
    "Bitcoin": {"type": "l7apps", "name": ["Bitcoin Core and Bitcoin Knots"]},
    "BitComet": {"type": "l7apps", "name": ["BitComet"]},
    "Bitly": {"type": "l7apps", "name": ["Bitly"]},
    "BitTorrent Protocol": {"type": "l7apps", "name": ["BitTorrent", "BitTorrent announce", "BitTorrent Scrape"]},
    "BitTorrent Sync": {"type": "l7apps", "name": ["BitTorrent", "BitTorrent announce", "BitTorrent Scrape"]},
    "BitTorrent Now": {"type": "l7apps", "name": ["BitTorrent", "BitTorrent announce", "BitTorrent Scrape"]},
    "BitTornado": {"type": "l7apps", "name": ["BitTorrent", "BitTorrent announce", "BitTorrent Scrape"]},
    "BitTyrant": {"type": "l7apps", "name": ["BitTorrent", "BitTorrent announce", "BitTorrent Scrape"]},
    "Blackboard": {"type": "l7apps", "name": ["Blackboard"]},
    "BlackPlanet": {"type": "l7apps", "name": ["BlackPlanet"]},
    "Blogger": {"type": "l7apps", "name": ["Blogger"]},
    "Bloomberg": {"type": "l7apps", "name": ["Bloomberg"]},
    "Bloomberg professional": {"type": "l7apps", "name": ["Bloomberg Professional"]},
    "bonpoo": {"type": "l7apps", "name": ["Bonpoo"]},
    "Booking.com": {"type": "l7apps", "name": ["Booking"]},
    "Bopup Messenger": {"type": "l7apps", "name": ["BopUp Messenger"]},
    "Box": {"type": "l7apps", "name": ["Box"]},
    "Browsec": {"type": "l7apps", "name": ["Browsec"]},
    "CafeMom": {"type": "l7apps", "name": ["CafeMom"]},
    "Caihong": {"type": "l7apps", "name": ["Caihong QQ"]},
    "Caihong-audio-video": {"type": "l7apps", "name": ["Caihong QQ"]},
    "CBS-video": {"type": "l7apps", "name": ["Viacom CBS"]},
    "Camfrog Video Chat": {"type": "l7apps", "name": ["Camfrog"]},
    "CBS-video": {"type": "l7apps", "name": ["Viacom CBS"]},
    "CANON BJNP Protocol": {"type": "l7apps", "name": ["Canon BJNP"]},
    "Chatango": {"type": "l7apps", "name": ["Chatango"]},
    "ChatWork": {"type": "l7apps", "name": ["ChatWork desktop", "ChatWork web"]},
    "Checkvist": {"type": "l7apps", "name": ["Checkvist"]},
    "Chess.com": {"type": "l7apps", "name": ["Chess.com"]},
    "Chikka-messenger": {"type": "l7apps", "name": ["Chikka"]},
    "Chrome Remote Desktop": {"type": "l7apps", "name": ["Chrome Remote Desktop"]},
    "Cisco AnyConnect": {"type": "l7apps", "name": ["Cisco VPN AnyConnect"]},
    "Cisco WebEx Meetings": {"type": "l7apps", "name": ["WebEx"]},
    "Cisco WebEx Meetings-Remote Control": {"type": "l7apps", "name": ["WebEx"]},
    "Cisco WebEx Meetings-file sharing": {"type": "l7apps", "name": ["WebEx file sharing"]},
    "Cisco WebEx Meetings-file transfer": {"type": "l7apps", "name": ["WebEx file sharing"]},
    "Citrix": {"type": "l7apps", "name": ["Citrix"]},
    "Citrix JEDI protocol": {"type": "l7apps", "name": ["Citrix Jedi"]},
    "Classmates": {"type": "l7apps", "name": ["Classmates"]},
    "ClickMeeting": {"type": "l7apps", "name": ["ClickMeeting"]},
    "Cloob": {"type": "l7apps", "name": ["Cloob"]},
    "CNN": {"type": "l7apps", "name": ["CNN"]},
    "CNN-video": {"type": "l7apps", "name": ["CNN"]},
    "CODESYS": {"type": "l7apps", "name": ["CodeSys"]},
    "CommFort": {"type": "l7apps", "name": ["CommFort"]},
    "Commvault": {"type": "l7apps", "name": ["Commvault"]},
    "Component Network over IP (CN/IP)": {"type": "l7apps", "name": ["Component Network over IP (CN/IP) (CEA 852)"]},
    "Concur": {"type": "l7apps", "name": ["Concur Solutions"]},
    "Convo": {"type": "l7apps", "name": ["Convo"]},
    "Craigslist": {"type": "l7apps", "name": ["Craigslist"]},
    "Crashplan": {"type": "l7apps", "name": ["CrashPlan"]},
    "CrossLoop": {"type": "l7apps", "name": ["CrossLoop"]},
    "CVSup": {"type": "l7apps", "name": ["CVSup"]},
    "CyberGhost VPN": {"type": "l7apps", "name": ["CyberGhost VPN"]},
    "Cyndicate": {"type": "l7apps", "name": ["Cyndicate"]},
    "DailyMotion": {"type": "l7apps", "name": ["Dailymotion"]},
    "Daum": {"type": "l7apps", "name": ["Daum"]},
    "Daum tvpot": {"type": "l7apps", "name": ["Daum MyPeople"]},
    "DB2": {"type": "l7apps", "name": ["DB2"]},
    "DCE-RPC Protocol": {"type": "l7apps", "name": ["DCERPC"]},
    "Dcinside": {"type": "l7apps", "name": ["dcinside"]},
    "Deezer": {"type": "l7apps", "name": ["Deezer"]},
    "Degoo": {"type": "l7apps", "name": ["Degoo"]},
    "Dell-DRAC": {"type": "l7apps", "name": ["Dell DRAC"]},
    "Deposit Files": {"type": "l7apps", "name": ["DepositFiles"]},
    "Desknet's": {"type": "l7apps", "name": ["desknets"]},
    "DHCP Protocol": {"type": "l7apps", "name": ["DHCP"]},
    "Diameter Protocol": {"type": "l7apps", "name": ["DIAMETER"]},
    "Dictionary.com": {"type": "l7apps", "name": ["Dictionary"]},
    "Digg": {"type": "l7apps", "name": ["Digg"]},
    "Digsby": {"type": "l7apps", "name": ["Digsby Beta"]},
    "Direct Connect": {"type": "l7apps", "name": ["Direct Connect"]},
    "Discord": {"type": "l7apps", "name": ["DiscordApp"]},
    "distcc": {"type": "l7apps", "name": ["distcc"]},
    "DivShare": {"type": "l7apps", "name": ["DivShare"]},
    "DLMS/COSEM(IEC62056)": {"type": "l7apps", "name": ["DLMS/COSEM"]},
    "DNF": {"type": "l7_category", "name": ["Software update"]},
    "DNP3 Protocol": {"type": "l7apps", "name": ["DNP3"]},
    "DNS Protocol": {"type": "l7apps", "name": ["DNS"]},
    "DNSCrypt": {"type": "l7apps", "name": ["DNSCrypt"]},
    "Docstoc": {"type": "l7apps", "name": ["Docstoc"]},
    "Doctor Web AntiVirus": {"type": "l7apps", "name": ["Dr Web Update"]},
    "DocuSign": {"type": "l7apps", "name": ["DocuSign"]},
    "Doodle-download": {"type": "l7apps", "name": ["Doodle"]},
    "DotVPN": {"type": "l7apps", "name": ["DotVPN"]},
    "Draugiem": {"type": "l7apps", "name": ["Draugiem"]},
    "Dreamstime": {"type": "l7apps", "name": ["DreamsTime"]},
    "DroidVPN": {"type": "l7apps", "name": ["DroidVPN"]},
    "Dropbox": {"type": "l7apps", "name": ["DropBox"]},
    "Dropbox paper": {"type": "l7apps", "name": ["Dropbox Lan Sync Protocol"]},
    "Dropbox-web": {"type": "l7apps", "name": ["Dropbox Web Download", "Dropbox Web Upload"]},
    "Dropbox-web download": {"type": "l7apps", "name": ["Dropbox Web Download"]},
    "Dropbox-web upload": {"type": "l7apps", "name": ["Dropbox Web Upload"]},
    "Dropmefiles": {"type": "l7apps", "name": ["DropMeFiles.com"]},
    "Dropmefiles-download": {"type": "l7apps", "name": ["DropMeFiles.com"]},
    "Dropmefiles-upload": {"type": "l7apps", "name": ["DropMeFiles.com"]},
    "DropSend": {"type": "l7apps", "name": ["DropSend"]},
    "Duolingo": {"type": "l7apps", "name": ["Duolingo"]},
    "earthcam": {"type": "l7apps", "name": ["EarthCam"]},
    "Easyprojects": {"type": "l7apps", "name": ["Easyprojects"]},
    "eBuddy": {"type": "l7apps", "name": ["eBuddy"]},
    "eFriend": {"type": "l7apps", "name": ["eFriend"]},
    "Egnyte": {"type": "l7apps", "name": ["Egnyte"]},
    "eHarmony": {"type": "l7apps", "name": ["eHarmony"]},
    "ELCOM 90 protocol": {"type": "l7apps", "name": ["Elcom"]},
    "EMC NetWorker": {"type": "l7apps", "name": ["EMC NetWorker"]},
    "eMule": {"type": "l7apps", "name": ["eMule"]},
    "Enchant": {"type": "l7apps", "name": ["Enchant"]},
    "EndNote": {"type": "l7apps", "name": ["EndNote"]},
    "Epic Browser": {"type": "l7apps", "name": ["Epic Browser VPN"]},
    "Epicurious": {"type": "l7apps", "name": ["Epicurious"]},
    "Epicurious-video": {"type": "l7apps", "name": ["Epicurious"]},
    "ESPN Player": {"type": "l7apps", "name": ["ESPN"]},
    "ESPN SportCenter": {"type": "l7apps", "name": ["ESPN"]},
    "ESPN Player-streaming": {"type": "l7apps", "name": ["ESPN"]},
    "Ether S Bus Protocol": {"type": "l7apps", "name": ["Ether-S-Bus"]},
    "Ether S I/O Protocol": {"type": "l7apps", "name": ["Ether-S-I/O"]},
    "EtherNet/IP": {"type": "l7apps", "name": ["EtherNet/IP"]},
    "Etsy": {"type": "l7apps", "name": ["Etsy"]},
    "Eventbrite": {"type": "l7apps", "name": ["Eventbrite"]},
    "Evernote": {"type": "l7apps", "name": ["Evernote"]},
    "Evernote-download": {"type": "l7apps", "name": ["Evernote"]},
    "Evernote-upload": {"type": "l7apps", "name": ["Evernote"]},
    "Evernote-sharing": {"type": "l7apps", "name": ["Evernote"]},
    "Evernote-posting": {"type": "l7apps", "name": ["Evernote"]},
    "Evernote-editing": {"type": "l7apps", "name": ["Evernote"]},
    "Facebook": {"type": "l7apps", "name": ["Facebook"]},
    "Facebook Apps": {"type": "l7apps", "name": ["Facebook Apps"]},
    "Facebook-chat": {"type": "l7apps", "name": ["Facebook  Chat"]},
    "Facebook Games": {"type": "l7apps", "name": ["Facebook Apps"]},
    "Facebook Groups": {"type": "l7apps", "name": ["Facebook"]},
    "Facebook Messenger": {"type": "l7apps", "name": ["Facebook  Chat"]},
    "Facebook-posting": {"type": "l7apps", "name": ["Facebook"]},
    "Facebook Social Plugins": {"type": "l7apps", "name": ["Facebook Apps"]},
    "Facebook-video": {"type": "l7apps", "name": ["Facebook Video"]},
    "Facebook-video-upload": {"type": "l7apps", "name": ["Facebook Video", "Facebook Upload"]},
    "FactSet": {"type": "l7apps", "name": ["FactSet"]},
    "Fastmail": {"type": "l7apps", "name": ["Fastmail"]},
    "FastStunnel": {"type": "l7apps", "name": ["FastStunnel"]},
    "FC2": {"type": "l7apps", "name": ["FC2"]},
    "FC2-video": {"type": "l7apps", "name": ["FC2"]},
    "FC2-video-upload": {"type": "l7apps", "name": ["FC2"]},
    "FCC Speed Test": {"type": "l7apps", "name": ["FCC Speed Test"]},
    "Fetion": {"type": "l7apps", "name": ["Fetion"]},
    "Fetion-audio-video": {"type": "l7apps", "name": ["Fetion"]},
    "Fetion-file-transfer": {"type": "l7apps", "name": ["Fetion"]},
    "File Dropper": {"type": "l7apps", "name": ["File Dropper"]},
    "FileDropper": {"type": "l7apps", "name": ["FileDropper"]},
    "FileCatalyst Direct ": {"type": "l7apps", "name": ["FileCatalyst"]},
    "Fileguri": {"type": "l7apps", "name": ["Fileguri"]},
    "FileMaker Pro": {"type": "l7apps", "name": ["FileMaker Pro"]},
    "FilesAnywhere": {"type": "l7apps", "name": ["FilesAnywhere"]},
    "FilePipe P2P": {"type": "l7apps", "name": ["Ares", "FastTrack", "Gnetella"]},
    "FineVPN-services": {"type": "l7apps", "name": ["Fine VPN"]},
    "Firefox": {"type": "l7apps", "name": ["Firefox"]},
    "FirePhoenix": {"type": "l7apps", "name": ["FirePhoenix"]},
    "fiverr": {"type": "l7apps", "name": ["Fiverr"]},
    "FIX protocol": {"type": "l7apps", "name": ["FIX (Financial Information eXchange)"]},
    "Flickr": {"type": "l7apps", "name": ["Flickr"]},
    "FlipDrive": {"type": "l7apps", "name": ["FlipDrive"]},
    "Flixster": {"type": "l7apps", "name": ["Flixster Movies"]},
    "Flixwagon": {"type": "l7apps", "name": ["Flixwagon"]},
    "Flixwagon-download": {"type": "l7apps", "name": ["Flixwagon Video"]},
    "FlyVPN": {"type": "l7apps", "name": ["FlyVPN SSL"]},
    "FortiClient-update": {"type": "l7apps", "name": ["FortiClient Update"]},
    "Fotki": {"type": "l7apps", "name": ["Fotki"]},
    "Foursquare": {"type": "l7apps", "name": ["Foursquare"]},
    "FreeCast": {"type": "l7apps", "name": ["FreeCast"]},
    "FreeGate": {"type": "l7apps", "name": ["Freegate"]},
    "FreeMyBrowser": {"type": "l7apps", "name": ["FreeMyBrowser"]},
    "Freshdesk": {"type": "l7apps", "name": ["Freshdesk"]},
    "Freshsales": {"type": "l7apps", "name": ["Freshsales"]},
    "Frigate": {"type": "l7apps", "name": ["Frigate VPN"]},
    "Fubar": {"type": "l7apps", "name": ["fubar.com"]},
    "Fuze Meeting": {"type": "l7apps", "name": ["Fuze Meeting"]},
    "G3 Torrent": {"type": "l7apps", "name": ["BitTorrent", "BitTorrent announce", "BitTorrent Scrape"]},
    "Gadu-Gadu": {"type": "l7apps", "name": ["Gadu Gadu"]},
    "GameSpy": {"type": "l7apps", "name": ["GameSpy"]},
    "Garena": {"type": "l7apps", "name": ["Garena"]},
    "GatherPlace": {"type": "l7apps", "name": ["GatherPlace"]},
    "Gbridge": {"type": "l7apps", "name": ["gBridge"]},
    "CORBA/GIOP Protocol": {"type": "l7apps", "name": ["GIOP Protocol"]},
    "Giphy": {"type": "l7apps", "name": ["GIPHY"]},
    "Gimme P2P": {"type": "l7apps", "name": ["Gnutella"]},
    "git": {"type": "l7apps", "name": ["Github", "Gitlab", "Git Smart Protocol"]},
    "GitHub": {"type": "l7apps", "name": ["Github"]},
    "GitHub-download": {"type": "l7apps", "name": ["Git Smart Protocol"]},
    "GitHub-editing": {"type": "l7apps", "name": ["Github", "Git Smart Protocol"]},
    "GitHub-posting": {"type": "l7apps", "name": ["Github", "Git Smart Protocol"]},
    "GitHub-upload": {"type": "l7apps", "name": ["Git Smart Protocol"]},
    "GitLab": {"type": "l7apps", "name": ["Gitlab"]},
    "GitLab-download": {"type": "l7apps", "name": ["Git Smart Protocol"]},
    "Gliffy": {"type": "l7apps", "name": ["Gliffy"]},
    "Gmail": {"type": "l7apps", "name": ["Gmail"]},
    "GMX": {"type": "l7apps", "name": ["GMX"]},
    "Gnutella Protocol": {"type": "l7apps", "name": ["Gnutella"]},
    "Gom VPN": {"type": "l7apps", "name": ["Gom VPN"]},
    "GoMeetNow": {"type": "l7apps", "name": ["GoMeetNow"]},
    "Goodreads": {"type": "l7apps", "name": ["Goodreads"]},
    "Google Meet-chat": {"type": "l7apps", "name": ["Google Chat"]},
    "Google Docs": {"type": "l7apps", "name": ["Google Docs"]},
    "Google Drive-web": {"type": "l7apps", "name": ["Google Drive"]},
    "Google Drive-enterprise": {"type": "l7apps", "name": ["Google Drive"]},
    "Google Finance": {"type": "l7apps", "name": ["Google Finance"]},
    "Google Maps": {"type": "l7apps", "name": ["Google Maps"]},
    "Google Meet": {"type": "l7apps", "name": ["Google Meet"]},
    "Google Services": {
        "type": "l7apps",
        "name": ["Google Chat", "Google Contacts", "Google Docs", "Google Drive", "Google Duo",
                 "Google Finance", "Google Hangouts", "Google Maps", "Google Meet"]
    },
    "GoToMeeting/GoToWebinar": {
        "type": "l7apps",
        "name": ["GoToMeeting app", "GoToMeeting audio", "GoToMeeting chat", "GoToMeeting web"]
    },
    "GoToMeeting/GoToWebinar-file transfer": {"type": "l7apps", "name": ["GoToMeeting app"]},
    "grooveshark": {"type": "l7apps", "name": ["GrooveShark"]},
    "Gnome Bittorrent": {"type": "l7apps", "name": ["BitTorrent", "BitTorrent announce", "BitTorrent Scrape"]},
    "Guardster": {"type": "l7apps", "name": ["Guardster"]},
    "Gyazo": {"type": "l7apps", "name": ["Gyazo"]},
    "H.323 Protocol": {"type": "l7apps", "name": ["H.323 Gatestat"]},
    "H.245 Protocol": {"type": "l7apps", "name": ["H245"]},
    "H.323 Protocol": {"type": "l7apps", "name": ["H323"]},
    "Hadoop": {"type": "l7apps", "name": ["HRPC (Hadoop RPC)"]},
    "Hart IP": {"type": "l7apps", "name": ["HART IP Protocol"]},
    "Hangouts": {"type": "l7apps", "name": ["Google Hangouts"]},
    "Hangouts-audio-video": {"type": "l7apps", "name": ["Google Hangouts"]},
    "Hangouts-chat": {"type": "l7apps", "name": ["Google Hangouts"]},
    "Hangouts-download": {"type": "l7apps", "name": ["Google Hangouts"]},
    "Hangouts-upload": {"type": "l7apps", "name": ["Google Hangouts"]},
    "HBO Go": {"type": "l7apps", "name": ["HBO Go"]},
    "HBO": {"type": "l7apps", "name": ["HBO Now"]},
    "High Level Data Link Control (HDLC Encapsulation)": {"type": "l7apps", "name": ["HDLC-OVER-TCP"]},
    "Hide.me": {"type": "l7apps", "name": ["Hide.me/vpn-free.pro UDP"]},
    "Hideman VPN": {"type": "l7apps", "name": ["Hideman VPN"]},
    "HideMe VPN": {"type": "l7apps", "name": ["HideMe TCP"]},
    "Hightail": {"type": "l7apps", "name": ["Hightail"]},
    "Hola": {"type": "l7apps", "name": ["Hola VPN"]},
    "Hotsuite": {"type": "l7apps", "name": ["Hotsuite"]},
    "Hotline Connect": {"type": "l7apps", "name": ["Hotline"]},
    "Hotspot Shield": {"type": "l7apps", "name": ["Hotspot Shield"]},
    "Hoxx VPN": {"type": "l7apps", "name": ["Hoxx/Setup VPN"]},
    "HTTP/2": {"type": "l7apps", "name": ["HTTP"]},
    "HTCondor": {"type": "l7apps", "name": ["Condor UDP"]},
    "HTTP/2 over TLS": {"type": "l7apps", "name": ["HTTPS"]},
    "HubSpot": {"type": "l7apps", "name": ["HubSpot"]},
    "HULFT": {"type": "l7apps", "name": ["HULFT"]},
    "Hulu": {"type": "l7apps", "name": ["Hulu"]},
    "Hyves-chat": {"type": "l7apps", "name": ["Hyves chat"]},
    "IceChat": {"type": "l7apps", "name": ["ICE Chat"]},
    "iChat": {"type": "l7apps", "name": ["iChat"]},
    "ICQ": {"type": "l7apps", "name": ["Web ICQ"]},
    "IEC 60870-5-104": {"type": "l7apps", "name": ["IEC 104"]},
    "IEC 60870-5-104 - ( IEC 101 ) Delay Acquistion Command": {"type": "l7apps", "name": ["IEC 104 ASDU"]},
    "Synchrophasor Protocol (IEEE C37.118)": {"type": "l7apps", "name": ["IEEE C37.118 Synchrophasor"]},
    "IKE Protocol": {"type": "l7apps", "name": ["IKE"]},
    "IMAP Protocol": {"type": "l7apps", "name": ["IMAP"]},
    "IMDb": {"type": "l7apps", "name": ["IMDb"]},
    "imgur": {"type": "l7apps", "name": ["Imgur"]},
    "Imo IM": {"type": "l7apps", "name": ["IMO IM"]},
    "IMVU": {"type": "l7apps", "name": ["IMVU"]},
    "indeed": {"type": "l7apps", "name": ["indeed"]},
    "Insightly CRM": {"type": "l7apps", "name": ["Insightly CRM"]},
    "Instagram": {"type": "l7apps", "name": ["Instagram"]},
    "Instagram-posting": {"type": "l7apps", "name": ["Instagram"]},
    "Instagram-video": {"type": "l7apps", "name": ["Instagram"]},
    "Instagram-upload": {"type": "l7apps", "name": ["Instagram"]},
    "InvisibleNET VPN": {"type": "l7apps", "name": ["InvisibleNET"]},
    "IPP (Internet Printing Protocol)": {"type": "l7apps", "name": ["IPP (Internet Printing Protocol)"]},
    "IRC Protocol": {"type": "l7apps", "name": ["IRC"]},
    "iRODS": {"type": "l7apps", "name": ["iRODS"]},
    "Internet Small Computer System Interface (iSCSI)": {"type": "l7apps", "name": ["iSCSI"]},
    "ISL Light": {"type": "l7apps", "name": ["ISL Light"]},
    "Issuu": {"type": "l7apps", "name": ["Issuu"]},
    "iStock": {"type": "l7apps", "name": ["iStock Photo"]},
    "Jabber Protocol (XMPP)": {"type": "l7apps", "name": ["XMPP"]},
    "Jango": {"type": "l7apps", "name": ["Jango"]},
    "Java Update": {"type": "l7apps", "name": ["Java Update Service"]},
    "Jenkins": {"type": "l7apps", "name": ["Jenkins CLI"]},
    "Jitsi Meet": {"type": "l7apps", "name": ["Jitsi Meet Online"]},
    "Jobber": {"type": "l7apps", "name": ["Jobber"]},
    "JoinMe": {"type": "l7apps", "name": ["Join me"]},
    "Jottacloud-upload": {"type": "l7apps", "name": ["Jottacloud"]},
    "Jottacloud-download": {"type": "l7apps", "name": ["Jottacloud"]},
    "JumboMail": {"type": "l7apps", "name": ["JumboMail"]},
    "JXTA Protocols": {"type": "l7apps", "name": ["JXTA Protocol"]},
    "Kanban Tool": {"type": "l7apps", "name": ["Kanban Tool"]},
    "Kaseya": {"type": "l7apps", "name": ["Kaseya"]},
    "Kaspersky Lab-update": {"type": "l7apps", "name": ["Kaspersky Update"]},
    "Kazaa Media Desktop": {"type": "l7apps", "name": ["Kazaa"]},
    "Kazaa Lite": {"type": "l7apps", "name": ["Kazaa"]},
    "Kerberos Protocol": {"type": "l7apps", "name": ["Kerberos5"]},
    "Kerika": {"type": "l7apps", "name": ["Kerika"]},
    "Kickserv": {"type": "l7apps", "name": ["Kickserv"]},
    "Kik": {"type": "l7apps", "name": ["Kik Messenger"]},
    "Kingsoft Services": {"type": "l7apps", "name": ["Kingsoft"]},
    "Knight Online": {"type": "l7apps", "name": ["Knight Online"]},
    "KNXnet/IP": {"type": "l7apps", "name": ["KNXNet/IP"]},
    "Kproxy": {"type": "l7apps", "name": ["Kproxy"]},
    "Last FM": {"type": "l7apps", "name": ["Last.fm"]},
    "LDAP Protocol": {"type": "l7apps", "name": ["LDAP"]},
    "LeBonCoin": {"type": "l7apps", "name": ["Leboncoin"]},
    "Libero Video": {"type": "l7apps", "name": ["Libero"]},
    "Lifesize": {"type": "l7apps", "name": ["LifeSize"]},
    "LINE": {"type": "l7apps", "name": ["LINE"]},
    "LinkedIn": {"type": "l7apps", "name": ["LinkedIn"]},
    "LiteManager": {"type": "l7apps", "name": ["Lite Manager"]},
    "live365": {"type": "l7apps", "name": ["Live365"]},
    "LiveJornal": {"type": "l7apps", "name": ["LiveJornal"]},
    "LogMeIn": {"type": "l7apps", "name": ["LogMeIn"]},
    "LogMeIn rescue": {"type": "l7apps", "name": ["LogMeIn login"]},
    "Mail.ru": {"type": "l7apps", "name": ["Mail.ru"]},
    "Mail.Ru Agent": {"type": "l7apps", "name": ["Mail.Ru Agent"]},
    "Mail.ru-mail": {"type": "l7apps", "name": ["Mail.ru"]},
    "Mail.Ru Agent-file transfer": {"type": "l7apps", "name": ["Mail.ru Cloud"]},
    "Mail.ru-cloud": {"type": "l7apps", "name": ["Mail.ru Cloud"]},
    "MailBigFile": {"type": "l7apps", "name": ["MailBigFile"]},
    "MailChimp": {"type": "l7apps", "name": ["MailChimp"]},
    "Manolito": {"type": "l7apps", "name": ["Manolito"]},
    "McAfee-update": {"type": "l7apps", "name": ["McAfee Update"]},
    "MediaFire": {"type": "l7apps", "name": ["MediaFire"]},
    "MediaGet": {"type": "l7apps", "name": ["MediaGet"]},
    "Meetup": {"type": "l7apps", "name": ["Meetup"]},
    "Mega": {"type": "l7apps", "name": ["Mega"]},
    "Megaproxy": {"type": "l7apps", "name": ["Megaproxy"]},
    "Memcached": {"type": "l7apps", "name": ["Memcached"]},
    "Metacafe": {"type": "l7apps", "name": ["Metacafe"]},
    "MGCP Protocol": {"type": "l7apps", "name": ["MGCP"]},
    "Microsoft Download Manager": {"type": "l7apps", "name": ["Microsoft Update", "WinUpdate"]},
    "Microsoft Edge": {"type": "l7apps", "name": ["Edge"]},
    "Microsoft Office Groove": {"type": "l7apps", "name": ["Groove"]},
    "Microsoft OneDrive": {"type": "l7apps", "name": ["OneDrive"]},
    "Microsoft OneDrive-web": {"type": "l7apps", "name": ["OneDrive"]},
    "Microsoft Outlook-web": {"type": "l7apps", "name": ["Outlook"]},
    "Microsoft Outlook-web-file transfer": {"type": "l7apps", "name": ["Outlook"]},
    "Microsoft Outlook-web-posting": {"type": "l7apps", "name": ["Outlook"]},
    "Microsoft Media Server (MMS)": {"type": "l7apps", "name": ["MS MMS"]},
    "Microsoft Teams": {"type": "l7apps", "name": ["MS Teams"]},
    "Microsoft Teams-download": {"type": "l7apps", "name": ["MS Teams File sharing & Chat"]},
    "Microsoft Teams-upload": {"type": "l7apps", "name": ["MS Teams File sharing & Chat"]},
    "Microsoft Teams-editing": {"type": "l7apps", "name": ["MS Teams File sharing & Chat"]},
    "Microsoft Teams-file transfer": {"type": "l7apps", "name": ["MS Teams File sharing & Chat"]},
    "Microsoft Teams-sharing": {"type": "l7apps", "name": ["MS Teams File sharing & Chat"]},
    "Microsoft Teams-posting": {"type": "l7apps", "name": ["MS Teams", "MS Teams File sharing & Chat"]},
    "Microsoft Teams-remote control": {"type": "l7apps", "name": ["MS Teams", "MS Teams File sharing & Chat"]},
    "Microsoft Teams-sharing": {"type": "l7apps", "name": ["MS Teams File sharing & Chat"]},
    "Microsoft Services": {"type": "applicationgroup", "name": ["Microsoft and Office365 Services"]},
    "Microsoft Store": {"type": "l7apps", "name": ["Microsoft Store"]},
    "Microsoft SQL Server (TDS Protocol)": {"type": "l7apps", "name": ["TDS (Tabular Data Stream)"]},
    "Microsoft Teams-Web Tab": {"type": "l7apps", "name": ["MS Teams"]},
    "Mikogo": {"type": "l7apps", "name": ["Mikogo"]},
    "MindMeister": {"type": "l7apps", "name": ["Mindmeister"]},
    "Mindomo": {"type": "l7apps", "name": ["Mindomo"]},
    "MinerGate": {"type": "l7apps", "name": ["MinerGate"]},
    "Miro": {"type": "l7apps", "name": ["Miro"]},
    "MissLee Messenger": {"type": "l7apps", "name": ["MissLee"]},
    "MMS Protocol": {"type": "l7apps", "name": ["MMS"]},
    "MocoSpace": {"type": "l7apps", "name": ["MocoSpace"]},
    "Modbus Protocol": {"type": "l7apps", "name": ["Modbus"]},
    "Monday": {"type": "l7apps", "name": ["Monday"]},
    "MongoDB": {"type": "l7apps", "name": ["MongoDB"]},
    "Moo": {"type": "l7apps", "name": ["Moo"]},
    "MQTT Protocol": {"type": "l7apps", "name": ["MQTT"]},
    "MS-Netlogon Protocol": {"type": "l7apps", "name": ["NETLOGON"]},
    "MSN-web": {"type": "l7apps", "name": ["MSN"]},
    "MSN Web Messenger": {"type": "l7apps", "name": ["MSN Messenger"]},
    "MTConnect": {"type": "l7apps", "name": ["MTConnect Protocol"]},
    "Munin": {"type": "l7apps", "name": ["Munin"]},
    "Mute": {"type": "l7apps", "name": ["Mute"]},
    "My-Files.RU": {"type": "l7apps", "name": ["My-Files"]},
    "MyGreenPC": {"type": "l7apps", "name": ["MyGreenPC"]},
    "MySpace": {"type": "l7apps", "name": ["myspace"]},
    "MySpace Video": {"type": "l7apps", "name": ["myspace"]},
    "MySQL Community Server": {"type": "l7apps", "name": ["MySQL"]},
    "NASA": {"type": "l7apps", "name": ["NASA"]},
    "NateOn": {"type": "l7apps", "name": ["NateOn", "NateOn desktop"]},
    "NateOn-audio video": {"type": "l7apps", "name": ["NateOn", "NateOn desktop", "NateOn VOIP"]},
    "NateOn-desctop sharing": {"type": "l7apps", "name": ["NateOn desktop"]},
    "Nate-video": {"type": "l7apps", "name": ["NateOn", "NateOn desktop", "NateOn VOIP"]},
    "Naver": {"type": "l7apps", "name": ["Naver"]},
    "NBA.com-video": {"type": "l7apps", "name": ["NBA", "NBA Turner"]},
    "NBC": {"type": "l7apps", "name": ["NBC News"]},
    "NBC News": {"type": "l7apps", "name": ["NBC News"]},
    "NBC-video": {"type": "l7apps", "name": ["NBC News"]},
    "Netease Webdisk": {"type": "l7apps", "name": ["Netease"]},
    "Netflix": {"type": "l7apps", "name": ["Netflix"]},
    "Netload": {"type": "l7apps", "name": ["NETLOAD"]},
    "Nexonia": {"type": "l7apps", "name": ["Nexonia"]},
    "NFS Protocol": {"type": "l7apps", "name": ["NFS"]},
    "Ngrok": {"type": "l7apps", "name": ["Ngrok"]},
    "Nimbuzz": {"type": "l7apps", "name": ["Nimbuzz Messenger"]},
    "Novell Filr": {"type": "l7apps", "name": ["Novell Filr"]},
    "NTP Protocol": {"type": "l7apps", "name": ["NTPv3", "NTPv4"]},
    "OCSP": {"type": "l7apps", "name": ["OCSP"]},
    "Odnoklassniki": {"type": "l7apps", "name": ["Odnoklassniki"]},
    "Odnoklassniki-apps": {"type": "l7apps", "name": ["Odnoklassniki"]},
    "Odnoklassniki-messaging": {"type": "l7apps", "name": ["Odnoklassniki"]},
    "Odnoklassniki-voice-video chat": {"type": "l7apps", "name": ["Odnoklassniki"]},
    "Office365-Outlook": {"type": "l7apps", "name": ["Office365"]},
    "Office365-Outlook-web": {"type": "l7apps", "name": ["Office365"]},
    "OkCupid": {"type": "l7apps", "name": ["OkCupid"]},
    "Omegle": {"type": "l7apps", "name": ["Omegle"]},
    "Omron FINS protocol": {"type": "l7apps", "name": ["Omron Fins UDP"]},
    "OnePageCRM": {"type": "l7apps", "name": ["OnePageCRM"]},
    "ooVoo": {"type": "l7apps", "name": ["ooVoo"]},
    "OPC Unified Architecture": {"type": "l7apps", "name": ["OPC UA"]},
    "OPC DA": {"type": "l7apps", "name": ["OPC DA"]},
    "OpenDrive": {"type": "l7apps", "name": ["OpenDrive"]},
    "OpenVPN": {"type": "l7apps", "name": ["OpenVPN tcp", "OpenVPN udp"]},
    "Opera": {"type": "l7apps", "name": ["Opera"]},
    "Opera VPN": {"type": "l7apps", "name": ["Opera VPN"]},
    "Oracle": {"type": "l7apps", "name": ["Oracle"]},
    "Origin": {"type": "l7apps", "name": ["Origin"]},
    "Outbrain": {"type": "l7apps", "name": ["Outbrain"]},
    "Outlook Web Access": {"type": "l7apps", "name": ["Outlook"]},
    "P2Ptv Remote Control": {"type": "l7apps", "name": ["PVU"]},
    "PacketiX VPN": {"type": "l7apps", "name": ["PacketiX"]},
    "PageKite": {"type": "l7apps", "name": ["PageKite"]},
    "Palringo Rich Messaging": {"type": "l7apps", "name": ["Palringo"]},
    "Paltalk": {"type": "l7apps", "name": ["Paltalk"]},
    "PANDA Security-update": {"type": "l7apps", "name": ["Panda update"]},
    "Pandora Mobile": {"type": "l7apps", "name": ["Pandora"]},
    "Pandora Radio": {"type": "l7apps", "name": ["Pandora"]},
    "Pastebin": {"type": "l7apps", "name": ["Pastebin"]},
    "PayPal": {"type": "l7apps", "name": ["PayPal"]},
    "pcAnywhere": {"type": "l7apps", "name": ["pcAnywhere"]},
    "pCloud": {"type": "l7apps", "name": ["pCloud"]},
    "PCoIP": {"type": "l7apps", "name": ["PCoIP"]},
    "Perforce": {"type": "l7apps", "name": ["Perforce"]},
    "Periscope": {"type": "l7apps", "name": ["Periscope"]},
    "Photobucket": {"type": "l7apps", "name": ["Photobucket"]},
    "Pic Collage": {"type": "l7apps", "name": ["Pic Collage"]},
    "Pichat": {"type": "l7apps", "name": ["Pichat"]},
    "Pinterest": {"type": "l7apps", "name": ["Pinterest"]},
    "Pipedrive": {"type": "l7apps", "name": ["Pipedrive"]},
    "Pivotal Tracker": {"type": "l7apps", "name": ["Pivotal Tracker"]},
    "Podio": {"type": "l7apps", "name": ["Podio"]},
    "POP3 Protocol": {"type": "l7apps", "name": ["POP3"]},
    "PostgreSQL Protocol": {"type": "l7apps", "name": ["PostgreSQL"]},
    "PPlive": {"type": "l7apps", "name": ["PPlive"]},
    "PPTP Protocol": {"type": "l7apps", "name": ["PPTP"]},
    "Prezi": {"type": "l7apps", "name": ["Prezi"]},
    "Privatix": {"type": "l7apps", "name": ["Privatix"]},
    "Profinet Protocol": {"type": "l7apps", "name": ["Profinet IO over DCERPC"]},
    "ProofHub": {"type": "l7apps", "name": ["ProofHub"]},
    "Proprietary Tunneling Tools": {"type": "l7_category", "name": ["Tunneling"]},
    "ProtonMail": {"type": "l7apps", "name": ["ProtonMail"]},
    "ProWorkflow": {"type": "l7apps", "name": ["ProWorkflow"]},
    "ProxyLocal": {"type": "l7apps", "name": ["ProxyLocal"]},
    "ProxySite": {"type": "l7apps", "name": ["Proxysite"]},
    "PureVPN": {"type": "l7apps", "name": ["purevpn"]},
    "PutLocker": {"type": "l7apps", "name": ["Putlocker"]},
    "Qik": {"type": "l7apps", "name": ["Qik Video"]},
    "Qik-video upload": {"type": "l7apps", "name": ["Qik Video"]},
    "Qik-video viewing": {"type": "l7apps", "name": ["Qik Video"]},
    "Qlik": {"type": "l7apps", "name": ["Qlik"]},
    "Qnext": {"type": "l7apps", "name": ["Qnext"]},
    "Quake3 Protocol": {"type": "l7apps", "name": ["Quake 4"]},
    "Quic Protocol(RFC 9000)": {"type": "l7apps", "name": ["QUIC"]},
    "Quic Protocol(proprietary)": {"type": "l7apps", "name": ["QUIC"]},
    "QuickBooks Online": {"type": "l7apps", "name": ["QuickBooks"]},
    "Quora": {"type": "l7apps", "name": ["Quora"]},
    "Qvod Player": {"type": "l7apps", "name": ["Qvod"]},
    "RADIUS Protocol": {"type": "l7apps", "name": ["Radius Protocol"]},
    "Radmin": {"type": "l7apps", "name": ["Radmin"]},
    "Raketu": {"type": "l7apps", "name": ["Raketu"]},
    "Rambler": {"type": "l7apps", "name": ["Rambler"]},
    "Rapidgator.net": {"type": "l7apps", "name": ["RAPIDGATOR"]},
    "Rapidshare": {"type": "l7apps", "name": ["RapidShare"]},
    "RaviShare": {"type": "l7apps", "name": ["Ravishare"]},
    "Raynet": {"type": "l7apps", "name": ["Raynet"]},
    "Razor": {"type": "l7apps", "name": ["Razor"]},
    "Rdio": {"type": "l7apps", "name": ["Rdio"]},
    "ReadyTalk": {"type": "l7apps", "name": ["ReadyTalk"]},
    "RealPlayer": {"type": "l7apps", "name": ["RealPlayer"]},
    "RealtimeBoard": {"type": "l7apps", "name": ["RealtimeBoard"]},
    "Reddit": {"type": "l7apps", "name": ["Reddit"]},
    "Redis": {"type": "l7apps", "name": ["Redis"]},
    "ResearchGate": {"type": "l7apps", "name": ["ResearchGate"]},
    "Riverbed RiOS": {"type": "l7apps", "name": ["Riverbed"]},
    "rsync": {"type": "l7apps", "name": ["Rsync"]},
    "RTCP Protocol": {"type": "l7apps", "name": ["RTCP"]},
    "RTMP Protocol": {"type": "l7apps", "name": ["RTMP"]},
    "Real Time Publish Subscribe Protocol (RTPS)": {"type": "l7apps", "name": ["RTPS"]},
    "RTSP Protocol": {"type": "l7apps", "name": ["RTSP"]},
    "RuneScape": {"type": "l7apps", "name": ["RuneScape"]},
    "RuTube Media Uploader": {"type": "l7apps", "name": ["Rutube"]},
    "S7 protocol": {"type": "l7apps", "name": ["S7Comm"]},
    "S7 Plus Protocol": {"type": "l7apps", "name": ["S7Comm Plus"]},
    "Saba Centra": {"type": "l7apps", "name": ["Saba Centra Meeting"]},
    "Salesforce": {"type": "l7apps", "name": ["Salesforce"]},
    "Salesforce Marketing Cloud": {"type": "l7apps", "name": ["Salesforce CRM"]},
    "SAP": {"type": "l7apps", "name": ["SAP"]},
    "Skinny Client Control Protocol (SCCP)": {"type": "l7apps", "name": ["SCCP"]},
    "Scribd": {"type": "l7apps", "name": ["Scribd"]},
    "Send Anywhere": {"type": "l7apps", "name": ["Send Anywhere"]},
    "Sendspace": {"type": "l7apps", "name": ["SendSpace"]},
    "ServiceNow": {"type": "l7apps", "name": ["ServiceNow"]},
    "SharePoint": {"type": "l7apps", "name": ["SharePoint"]},
    "SharePoint-online": {"type": "l7apps", "name": ["SharePoint"]},
    "SharePoint-online-posting": {"type": "l7apps", "name": ["SharePoint"]},
    "SharePoint-documents": {"type": "l7apps", "name": ["SharePoint"]},
    "SharePoint - Login failed": {"type": "l7apps", "name": ["SharePoint"]},
    "SharePoint - Login succeeded": {"type": "l7apps", "name": ["SharePoint"]},
    "Shazam": {"type": "l7apps", "name": ["Shazam"]},
    "Shutterstock": {"type": "l7apps", "name": ["ShutterStock"]},
    "Shutterstock-download": {"type": "l7apps", "name": ["ShutterStock"]},
    "Shutterstock-upload": {"type": "l7apps", "name": ["ShutterStock"]},
    "Signal": {"type": "l7apps", "name": ["Signal Messenger"]},
    "SignEasy": {"type": "l7apps", "name": ["SignEasy"]},
    "Signiant": {"type": "l7apps", "name": ["Signiant"]},
    "SimpleHelp": {"type": "l7apps", "name": ["SimpleHelp"]},
    "Simplite-msn": {"type": "l7apps", "name": ["SimpLite MSN"]},
    "Sina-Weibo": {"type": "l7apps", "name": ["Sina Weibo"]},
    "SIP Protocol": {"type": "l7apps", "name": ["SIP"]},
    "Skydur": {"type": "l7apps", "name": ["Skydur"]},
    "Skype": {"type": "l7apps", "name": ["Skype"]},
    "Skype for Business (Lunc)": {"type": "l7apps", "name": ["Skype for Business"]},
    "Skype for Business (Lunc)-sharing": {
        "type": "l7apps",
        "name": ["Skype for Business", "Skype for business desktop sharing", "Skype for business File Transfer"]
    },
    "Skype for Business (Lunc)-video and voip": {
        "type": "l7apps",
        "name": ["Skype for Business", "Skype for business desktop sharing", "Skype for business File Transfer"]
    },
    "Skype - Video Chat": {"type": "l7apps", "name": ["Skype Chat", "Skype Call"]},
    "Slack": {"type": "l7apps", "name": ["Slack"]},
    "Slack-audio": {"type": "l7apps", "name": ["Slack"]},
    "Slack-chat": {"type": "l7apps", "name": ["Slack"]},
    "Slack-download": {"type": "l7apps", "name": ["Slack"]},
    "Slack-upload": {"type": "l7apps", "name": ["Slack"]},
    "SlideShare": {"type": "l7apps", "name": ["SlideShare"]},
    "Sling TV": {"type": "l7apps", "name": ["Sling"]},
    "Smallpdf-upload": {"type": "l7apps", "name": ["Smallpdf"]},
    "Smallpdf-download": {"type": "l7apps", "name": ["Smallpdf"]},
    "Smartfile": {"type": "l7apps", "name": ["SmartFile"]},
    "Smartsheet": {"type": "l7apps", "name": ["Smartsheet"]},
    "Server Message Block (SMB)": {"type": "l7apps", "name": ["SMB"]},
    "Server Message Block v2 (SMBv2)": {"type": "l7apps", "name": ["SMB2"]},
    "Server Message Block v3 (SMBv3)": {"type": "l7apps", "name": ["SMBv3"]},
    "SMTP Protocol": {"type": "l7apps", "name": ["SMTP"]},
    "Smugmug": {"type": "l7apps", "name": ["SmugMug"]},
    "Snapchat": {"type": "l7apps", "name": ["Snapchat"]},
    "SNMP Protocol": {"type": "l7apps", "name": ["SNMP v1", "SNMP v2"]},
    "SNMPv3": {"type": "l7apps", "name": ["SNMP v3"]},
    "Softros LAN Messenger": {"type": "l7apps", "name": ["Softros"]},
    "Sogou Map": {"type": "l7apps", "name": ["SogouMap"]},
    "Sohu": {"type": "l7apps", "name": ["Sohu"]},
    "Sohu video-upload": {"type": "l7apps", "name": ["Sohu"]},
    "Sohu Weibo": {"type": "l7apps", "name": ["Sohu"]},
    "Sohu Weibo-upload image": {"type": "l7apps", "name": ["Sohu"]},
    "Sohu Weibo-posting": {"type": "l7apps", "name": ["Sohu"]},
    "Sohu-video": {"type": "l7apps", "name": ["Sohu"]},
    "Solidfiles": {"type": "l7apps", "name": ["SolidFiles"]},
    "Soonr-download": {"type": "l7apps", "name": ["Soonr"]},
    "Soonr-upload": {"type": "l7apps", "name": ["Soonr"]},
    "Sopcast": {"type": "l7apps", "name": ["SopCast"]},
    "SoulSeek": {"type": "l7apps", "name": ["Soulseek"]},
    "SoundCloud": {"type": "l7apps", "name": ["SoundCloud"]},
    "SoundCloud-download": {"type": "l7apps", "name": ["SoundCloud"]},
    "SoundCloud-upload": {"type": "l7apps", "name": ["SoundCloud"]},
    "SourceForge": {"type": "l7apps", "name": ["SourceForge"]},
    "Speedtest.net": {"type": "l7apps", "name": ["Speedtest.net"]},
    "SpiderOak": {"type": "l7apps", "name": ["SpiderOak"]},
    "Splashtop Remote": {"type": "l7apps", "name": ["Splashtop"]},
    "Splunk": {"type": "l7apps", "name": ["Splunk"]},
    "Spotify": {"type": "l7apps", "name": ["Spotify"]},
    "SSDP": {"type": "l7apps", "name": ["SSDP"]},
    "SSH Protocol": {"type": "l7apps", "name": ["SSH"]},
    "SSL Protocol": {"type": "l7apps", "name": ["SSL"]},
    "StarCraft II": {"type": "l7apps", "name": ["StarCraft II"]},
    "Stealthy": {"type": "l7apps", "name": ["Stealthy"]},
    "Steam": {"type": "l7apps", "name": ["Steam"]},
    "Stitch": {"type": "l7apps", "name": ["Stitch"]},
    "Stitcher": {"type": "l7apps", "name": ["Stitcher Radio"]},
    "StockStar": {"type": "l7apps", "name": ["STOCKSTAR"]},
    "Stocktwits": {"type": "l7apps", "name": ["Stocktwits"]},
    "Stratum mining protocol": {"type": "l7apps", "name": ["Stratum"]},
    "SugarCRM": {"type": "l7apps", "name": ["SugarCRM"]},
    "Sumologic": {"type": "l7apps", "name": ["Sumo Logic"]},
    "SuperVPM": {"type": "l7apps", "name": ["SuperVPM"]},
    "Supremo": {"type": "l7apps", "name": ["Supremo Remote Desktop"]},
    "Surfshark": {"type": "l7apps", "name": ["Surfshark VPN"]},
    "Surveymonkey": {"type": "l7apps", "name": ["SurveyMonkey"]},
    "SVT Play": {"type": "l7apps", "name": ["SVT"]},
    "Sybase-SQL Anywhere": {"type": "l7apps", "name": ["Sybase"]},
    "Symantec-update": {"type": "l7apps", "name": ["Symantec Update"]},
    "Sync": {"type": "l7apps", "name": ["Sync"]},
    "Synergy2": {"type": "l7apps", "name": ["Synergy"]},
    "Syslog Protocol": {"type": "l7apps", "name": ["Syslog"]},
    "TACACS Protocol": {"type": "l7apps", "name": ["TACACS+ Protocol"]},
    "Tagged": {"type": "l7apps", "name": ["Tagged"]},
    "Tales Runner": {"type": "l7apps", "name": ["Tales Runner"]},
    "Tango": {"type": "l7apps", "name": ["Tango"]},
    "TeamSpeak": {"type": "l7apps", "name": ["TeamSpeak"]},
    "TeamViewer": {"type": "l7apps", "name": ["TeamViewer"]},
    "TeamViewer-web-Join Meeting": {"type": "l7apps", "name": ["TeamViewer"]},
    "TeamViewer-web-Management Console": {"type": "l7apps", "name": ["TeamViewer"]},
    "Teamwork": {"type": "l7apps", "name": ["Teamwork"]},
    "Telegram": {"type": "l7apps", "name": ["Telegram for Web"]},
    "Telegram-call": {"type": "l7apps", "name": ["Telegram for Web"]},
    "Telnet Protocol": {"type": "l7apps", "name": ["Telnet Protocol"]},
    "Teredo Protocol": {"type": "l7apps", "name": ["Teredo"]},
    "TikTok": {"type": "l7apps", "name": ["TikTok"]},
    "TNS Protocol": {"type": "l7apps", "name": ["TNS"]},
    "Tor": {"type": "l7apps", "name": ["Tor"]},
    "TouchVPN": {"type": "l7apps", "name": ["TouchVPN"]},
    "Torrent Swapper": {"type": "l7apps", "name": ["BitTorrent", "BitTorrent announce", "BitTorrent Scrape"]},
    "Torrent Monster": {"type": "l7apps", "name": ["BitTorrent", "BitTorrent announce", "BitTorrent Scrape"]},
    "Tumblr": {"type": "l7apps", "name": ["Tumblr"]},
    "TunnelBear": {"type": "l7apps", "name": ["TunnelBear"]},
    "Turbo VPN": {"type": "l7apps", "name": ["Turbo VPN"]},
    "Turbo Torrent": {"type": "l7apps", "name": ["BitTorrent"]},
    "TvAnts": {"type": "l7apps", "name": ["Tvants"]},
    "Twitch.tv-video play": {"type": "l7apps", "name": ["Twitch"]},
    "Twitch.tv-video access": {"type": "l7apps", "name": ["Twitch"]},
    "Twitter": {"type": "l7apps", "name": ["Twitter"]},
    "Twitter Social Plugins": {"type": "l7apps", "name": ["Twitter", "Twitter Posting"]},
    "Twoo": {"type": "l7apps", "name": ["Twoo"]},
    "Uber": {"type": "l7apps", "name": ["Uber"]},
    "UberConference": {"type": "l7apps", "name": ["UberConference"]},
    "Ultrasurf Chrome extension": {"type": "l7apps", "name": ["UltraSurf VPN extension"]},
    "Ultraviewer": {"type": "l7apps", "name": ["Ultraviewer"]},
    "Unlimited VPN": {"type": "l7apps", "name": ["VPN Unlimited"]},
    "Upload.info": {"type": "l7apps", "name": ["Upload.in"]},
    "Urban Dictionary": {"type": "l7apps", "name": ["Urban Dictionary"]},
    "Userlike": {"type": "l7apps", "name": ["Userlike"]},
    "Vagaa": {"type": "l7apps", "name": ["Vagaa TCP", "Vagaa UDP"]},
    "vBulletin": {"type": "l7apps", "name": ["vBulletin"]},
    "Ventrilo": {"type": "l7apps", "name": ["Ventrilo"]},
    "Vevo": {"type": "l7apps", "name": ["VEVO"]},
    "Viber": {"type": "l7apps", "name": ["Viber"]},
    "Viber-file-transfer": {"type": "l7apps", "name": ["Viber Upload"]},
    "Vidyo": {"type": "l7apps", "name": ["Vidyo"]},
    "Vimeo": {"type": "l7apps", "name": ["Vimeo"]},
    "ViPNet VPN": {"type": "l7apps", "name": ["VipNet Client 4.5"]},
    "Vision Helpdesk": {"type": "l7apps", "name": ["Vision Helpdesk"]},
    "VisionProject": {"type": "l7apps", "name": ["VisionProject"]},
    "Azure Visual Studio": {"type": "l7apps", "name": ["Visual Studio"]},
    "Vkontakte": {"type": "l7apps", "name": ["VK"]},
    "Vkontakte-chat": {"type": "l7apps", "name": ["VK"]},
    "Vkontakte-messaging": {"type": "l7apps", "name": ["VK"]},
    "Vkontakte-posting": {"type": "l7apps", "name": ["VK"]},
    "Vkontakte-multimedia": {"type": "l7apps", "name": ["VK Media"]},
    "VNC": {"type": "l7apps", "name": ["VNC"]},
    "Voddler": {"type": "l7apps", "name": ["Voddler"]},
    "Vox": {"type": "l7apps", "name": ["Vox Media"]},
    "VPN 360 and Unlimited VPN": {"type": "l7apps", "name": ["VPN 360"]},
    "VSee": {"type": "l7apps", "name": ["VSee"]},
    "Vuze": {"type": "l7apps", "name": ["Vuse"]},
    "VZOchat": {"type": "l7apps", "name": ["VZOChat"]},
    "Warez": {"type": "l7apps", "name": ["Warez P2P Client"]},
    "WEB.DE-mail": {"type": "l7apps", "name": ["Web.de"]},
    "WebDAV Protocol": {"type": "l7apps", "name": ["WebDav"]},
    "WebEx Webinars and Online Events": {"type": "l7apps", "name": ["WebEx"]},
    "WebSocket Protocol": {"type": "l7apps", "name": ["Websocket"]},
    "WeChat": {"type": "l7apps", "name": ["WeChat"]},
    "WeChat-file transfer": {"type": "l7apps", "name": ["WeChat"]},
    "WeChat-audio video chat": {"type": "l7apps", "name": ["WeChat"]},
    "Weico": {"type": "l7apps", "name": ["Weico iPhone"]},
    "Weiyun": {"type": "l7apps", "name": ["Weiyun"]},
    "WeTransfer": {"type": "l7apps", "name": ["WeTransfer"]},
    "WeTransfer-download": {"type": "l7apps", "name": ["WeTransfer"]},
    "WeTransfer-upload": {"type": "l7apps", "name": ["WeTransfer"]},
    "WhatsApp Messenger": {"type": "l7apps", "name": ["WhatsApp", "WhatsApp Chat", "WhatsApp Media"]},
    "WhatsApp Messenger-file transfer": {"type": "l7apps", "name": ["WhatsApp Media"]},
    "WhatsApp Messenger-voice call": {"type": "l7apps", "name": ["WhatsApp"]},
    "WhatsApp Messenger-web/PC": {"type": "l7apps", "name": ["WhatsApp", "WhatsApp Chat", "WhatsApp Media"]},
    "When I Work": {"type": "l7apps", "name": ["When I Work"]},
    "Wickr": {"type": "l7apps", "name": ["Wickr"]},
    "Wiley": {"type": "l7apps", "name": ["Wiley"]},
    "Windscribe": {"type": "l7apps", "name": ["Windscribe"]},
    "Windows Azure Cloud Services": {"type": "l7apps", "name": ["Microsoft Azure"]},
    "Windows Update": {"type": "l7apps", "name": ["WinUpdate", "Microsoft Update"]},
    "Windows Server Update Service (WSUS)": {"type": "l7apps", "name": ["WinUpdate", "Microsoft Update"]},
    "Windows Remote Management - WinRm": {"type": "l7apps", "name": ["PSRemoting (WinRM)"]},
    "Wire": {"type": "l7apps", "name": ["Wire"]},
    "Wireguard Tunnel Protocol": {"type": "l7apps", "name": ["Wireguard Protocol"]},
    "Wix.com": {"type": "l7apps", "name": ["Wix"]},
    "Wolfenstein-Enemy Territory": {"type": "l7apps", "name": ["Wolfenstein"]},
    "Wonderfile": {"type": "l7apps", "name": ["WonderFile"]},
    "WordPress": {"type": "l7apps", "name": ["WordPress"]},
    "World Of Tanks": {"type": "l7apps", "name": ["World of Tanks"]},
    "Wuala": {"type": "l7apps", "name": ["Wuala"]},
    "Xbox Live": {"type": "l7apps", "name": ["Xbox Live"]},
    "Xero": {"type": "l7apps", "name": ["Xero"]},
    "Xunlei": {"type": "l7apps", "name": ["Xunlei"]},
    "Xware-xTRM": {"type": "l7apps", "name": ["Xware xTrm"]},
    "Yahoo! Messenger": {"type": "l7apps", "name": ["Yahoo Messenger"]},
    "Yahoo! Messenger-upload": {"type": "l7apps", "name": ["Yahoo file transfer"]},
    "Yandex": {
        "type": "l7apps",
        "name": ["Yandex Browser", "Yandex Mail", "Yandex Maps", "Yandex Market", "Yandex Messenger",
                 "Yandex Music", "YandexEfir", "Yandex Taxi", "Yandex telemost", "Yandex telemost call",
                 "Yandex Translate", "Yandex.Disk", "Yandex.Disk download", "Yandex.Disk upload", "Yandex.Money"]
     },
    "Yandex Browser": {"type": "l7apps", "name": ["Yandex Browser"]},
    "Yandex-disk": {"type": "l7apps", "name": ["Yandex.Disk"]},
    "Yandex-disk-download": {"type": "l7apps", "name": ["Yandex.Disk download"]},
    "Yandex-disk-upload": {"type": "l7apps", "name": ["Yandex.Disk upload"]},
    "Yandex Mail": {"type": "l7apps", "name": ["Yandex Mail"]},
    "Yandex-maps": {"type": "l7apps", "name": ["Yandex Maps"]},
    "Yandex-multimedia": {"type": "l7apps", "name": ["Yandex Music", "YandexEfir"]},
    "Yelp": {"type": "l7apps", "name": ["Yelp"]},
    "Yoics": {"type": "l7apps", "name": ["Yoics"]},
    "Yosemite Server Backup": {"type": "l7apps", "name": ["Yosemite Backup"]},
    "Your Freedom": {"type": "l7apps", "name": ["Your Freedom VPN"]},
    "YouTube": {"type": "l7apps", "name": ["YouTube"]},
    "YouTube-upload": {"type": "l7apps", "name": ["YouTube Upload"]},
    "Yuuguu": {"type": "l7apps", "name": ["Yuuguu"]},
    "YY Voice": {"type": "l7apps", "name": ["YY Voice"]},
    "Zabbix": {"type": "l7apps", "name": ["Zabbix"]},
    "Zapier": {"type": "l7apps", "name": ["Zapier"]},
    "Zello": {"type": "l7apps", "name": ["Zello"]},
    "Zendesk": {"type": "l7apps", "name": ["Zendesk"]},
    "Zenefits": {"type": "l7apps", "name": ["Zenefits"]},
    "ZenMate": {"type": "l7apps", "name": ["ZenMate Browser Extension"]},
    "ZeroTier One": {"type": "l7apps", "name": ["ZeroTier"]},
    "Zippyshare": {"type": "l7apps", "name": ["zippyshare", "Zippyshare"]},
    "Zoom": {"type": "l7apps", "name": ["Zoom"]},
    "Zoom-chat": {"type": "l7apps", "name": ["Zoom chat"]},
    "Zoom-file transfer": {"type": "l7apps", "name": ["Zoom file sharing"]},
    "Zovine Messenger": {"type": "l7apps", "name": ["Zovine Messenger"]},
}

new_applicationgroup = [
    {   "name": "Cloud Services",
        "app_list": [
            "Bearlo Cloud",
            "CloudCall",
            "Cloudinary",
            "CloudTrax",
            "Fastly Cloud",
            "Filecloud.me",
            "FutureNetCloud",
            "GetFileCloud",
            "Jottacloud",
            "Mail.ru Cloud",
            "pCloud",
            "SoundCloud",
            "VideoMost Cloud",
        ]
    },
    {
        "name": "Download Manager",
        "app_list": [
            "Internet Download Manager",
            "OnlyOffice Download File",
            "BitTorrent",
            "BitTorrent announce",
            "BitTorrent Scrape",
            "Nyaa Torrents",
            f"{chr(956)}Torrent",
            "GetSpace",
            "MediaGet",
            "FlashGet DNS",
            "FlashGet HTTP",
            "FlashGet TCP",
            "FlashGet UDP",
        ]
    },
    {
        "name": "File Upload",
        "app_list": [
            "Amazon Chime upload/download",
            "Dropbox Web Upload",
            "Facebook Upload",
            "OnlyOffice Upload File",
            "Proton Drive upload/download",
            "Upload.in",
            "UploadFile",
            "Viber Upload",
            "Webinar uploading",
            "Yandex.Disk upload",
            "YouTube Upload",
        ]
    },
    {
        "name": "Media Sharing",
        "app_list": [
            "Amazon Chime upload/download",
            "Dropbox Web Download",
            "Dropbox Web Upload",
            "Facebook Upload",
            "Internet Download Manager",
            "OnlyOffice Download File",
            "OnlyOffice Upload File",
            "Proton Drive upload/download",
            "Upload.in",
            "UploadFile",
            "Viber Upload",
            "Webinar uploading",
            "Yandex.Disk download",
            "Yandex.Disk upload",
            "YouTube Upload",
        ]
    },
    {
        "name": "Microsoft and Office365 Services",
        "app_list": [
            "Groove",
            "Live Meeting",
            "Live Mesh",
            "Microsoft Azure",
            "Microsoft Defender",
            "Microsoft Delivery optimization",
            "Microsoft Exchange",
            "Microsoft location services",
            "Microsoft login",
            "Microsoft maps",
            "Microsoft Outlook Mobile",
            "Microsoft SCOM",
            "Microsoft Store",
            "Microsoft telemetry",
            "Microsoft Update",
            "Microsoft Whiteboard",
            "MS MMS",
            "MS Teams",
            "MS Teams File sharing & Chat",
            "MSN",
            "NSPlayer",
            "Office365",
            "OneDrive",
            "Outlook",
            "SharePoint",
            "Skype",
            "Skype Call",
            "Skype Chat",
            "Skype for Business",
            "Skype for business desktop sharing",
            "Skype for business File Transfer",
            "Skype screen sharing",
            "Visual Studio",
            "WinUpdate",
            "WMV",
        ]
    },
    {
        "name": "Instant Chat",
        "app_list": [
            "1C-Connect chat",
            "Amazon Chime chat",
            "Blackboard Chat",
            "Chatango",
            "ChatWork desktop",
            "ChatWork web",
            "Facebook  Chat",
            "Digsby Beta",
            "Google Chat",
            "GoToMeeting chat",
            "eBuddy",
            "eBuddy for Android",
            "Hipchat",
            "Hotline",
            "Hyves chat",
            "ICE Chat",
            "iChat",
            "IRC chat",
            "KakaoTalk chat",
            "Linkchat",
            "MS Teams File sharing & Chat",
            "MySpaceIM",
            "Paltalk",
            "Pichat",
            "Rocket.Chat",
            "Rocket.Chat Files",
            "Rocket.Chat Messages",
            "Skype Chat",
            "Snapchat",
            "Talk-me",
            "Qnext",
            "VZOChat",
            "WeChat",
            "WhatsApp Chat",
            "Xchat",
            "xntalk",
            "Zoom chat",
            "Zulipchat",
        ]
    }
]
