#!/usr/bin/python3

l7_categories = {
    'Business',
    'Coin Miners',
    'Conferencing',
    'Email',
    'File sharing P2P',
    'File storage and backup',
    'Games',
    'Instant messaging',
    'Media streaming',
    'Mobile',
    'Proxies and anonymizers',
    'Remote access',
    'Social networking',
    'Software update',
    'Standard networks',
    'Trojan Horses',
    'Tunneling',
    'VOIP',
    'Web browsing',
    'Web posting',
}

l7_categories_compliance = {
    'Coin_Miners': 'Coin Miners',
    'File_sharing_P2P': 'File sharing P2P',
    'File_storage_and_backup': 'File storage and backup',
    'Instant_messaging': 'Instant messaging',
    'Media_streaming': 'Media streaming',
    'Proxies_and_anonymizers': 'Proxies and anonymizers',
    'Remote_Access': 'Remote access',
    'Social_Networking': 'Social networking',
    'Software_Update': 'Software update',
    'Standard_Networks': 'Standard networks',
    'Trojan_Horses': 'Trojan Horses',
    'Web_browsing': 'Web browsing',
    'Web_posting': 'Web posting',
}

cp_app_category = {
    "Anonymizer": {
        "type": "app-url-category",
        "l7_category": ["Proxies and anonymizers"],
        "url_category": ["Anonymizers"],
        "applicationgroup": []
    },
    "Alcohol & Tobacco": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Alcohol & Tobacco"],
        "applicationgroup": []
    },
    "Artificial Intelligence (AI)": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Chat-bot AI"],
        "applicationgroup": []
    },
    "Blogs / Personal Pages": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Personal Sites"],
        "applicationgroup": []
    },
    "Botnets": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Botnets"],
        "applicationgroup": []
    },
    "Business / Economy": {
        "type": "app-url-category",
        "l7_category": ["Business"],
        "url_category": ["Business"],
        "applicationgroup": []
    },
    "Child Abuse": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Child Abuse Images"],
        "applicationgroup": []
    },
    "Cloud Services": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": [],
        "applicationgroup": ["Cloud Services"]
    },
    "Computers / Internet": {
        "type": "app-url-category",
        "l7_category": ["Standard networks"],
        "url_category": [],
        "applicationgroup": []
    },
    "Critical Risk": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Reputation: High risk"],
        "applicationgroup": []
    },
    "Cryptocurrency": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Cryptocurrency Mining"],
        "applicationgroup": []
    },
    "Download Manager": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": [],
        "applicationgroup": ["Download Manager"]
    },
    "Education": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Education"],
        "applicationgroup": []
    },
    "Email": {
        "type": "app-url-category",
        "l7_category": ["Email"],
        "url_category": [],
        "applicationgroup": []
    },
    "Encrypts communications": {
        "type": "app-url-category",
        "l7_category": ["Tunneling", "Proxies and anonymizer"],
        "url_category": ["Anonymizers"],
        "applicationgroup": []
    },
    "Entertainment": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Entertainment"],
        "applicationgroup": []
    },
    "Fashion": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Fashion & Beauty"],
        "applicationgroup": []
    },
    "File Storage and Sharing": {
        "type": "app-url-category",
        "l7_category": ["File storage and backup"],
        "url_category": ["Personal Storage"],
        "applicationgroup": []
    },
    "File Upload": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": [],
        "applicationgroup": ["File Upload"]
    },
    "Financial Services": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Finance"],
        "applicationgroup": []
    },
    "Gambling": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Gambling"],
        "applicationgroup": []
    },
    "Games": {
        "type": "app-url-category",
        "l7_category": ["Games"],
        "url_category": ["Games"],
        "applicationgroup": []
    },
    "Government / Military": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Government", "Military"],
        "applicationgroup": []
    },
    "High Risk": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Reputation: High risk"],
        "applicationgroup": []
    },
    "Hacking": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Hacking"],
        "applicationgroup": []
    },
    "Hate / Racism": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Hate & Intolerance"],
        "applicationgroup": []
    },
    "Health": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Health & Medicine"],
        "applicationgroup": []
    },
    "High Bandwidth": {
        "type": "app-url-category",
        "l7_category": ["Proxies and anonymizer", "File sharing P2P", "File storage and backup"],
        "url_category": ["Anonymizers", "Peer-to-Peer", "Personal Storage"],
        "applicationgroup": []
    },
    "Illegal / Questionable": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Tasteless", "Violence", "Criminal Activity", "Hate & Intolerance", "Profanity"],
        "applicationgroup": []
    },
    "Illegal Drugs": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Illegal Drug"],
        "applicationgroup": []
    },
    "Inactive Sites": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Parked Domains", "General"],
        "applicationgroup": []
    },
    "Instant Chat": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Chat", "Instant Messaging"],
        "applicationgroup": ["Instant Chat"]
    },
    "Instant Messaging": {
        "type": "app-url-category",
        "l7_category": ["Instant messaging"],
        "url_category": ["Instant Messaging"],
        "applicationgroup": []
    },
    "Job Search / Careers": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Job Search"],
        "applicationgroup": []
    },
    "Lingerie and Swimsuit / Suggestive": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Nudity"],
        "applicationgroup": []
    },
    "Marijuana": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Illegal Drug"],
        "applicationgroup": []
    },
    "Media Sharing": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": [],
        "applicationgroup": ["Media Sharing"]
    },
    "Media Streams": {
        "type": "app-url-category",
        "l7_category": ["Media streaming"],
        "url_category": [],
        "applicationgroup": []
    },
    "Medium Risk": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Reputation: Medium risk"],
        "applicationgroup": []
    },
    "Microsoft & Office365 Services": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": [],
        "applicationgroup": ["Microsoft and Office365 Services"]
    },
    "Mobile Software": {
        "type": "app-url-category",
        "l7_category": ["Mobile"],
        "url_category": [],
        "applicationgroup": []
    },
    "Network Protocols": {
        "type": "app-url-category",
        "l7_category": ["Standard networks"],
        "url_category": [],
        "applicationgroup": []
    },
    "Network Utilities": {
        "type": "app-url-category",
        "l7_category": ["Standard networks"],
        "url_category": [],
        "applicationgroup": []
    },
    "News / Media": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["News"],
        "applicationgroup": []
    },
    "Newsgroups / Forums": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Forums & Newsgroups"],
        "applicationgroup": []
    },
    "Nudity": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Nudity"],
        "applicationgroup": []
    },
    "P2P File Sharing": {
        "type": "app-url-category",
        "l7_category": ["File sharing P2P"],
        "url_category": [],
        "applicationgroup": []
    },
    "Personals / Dating": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Dating & Personals"],
        "applicationgroup": []
    },
    "Phishing": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Phishing & Fraud"],
        "applicationgroup": []
    },
    "Political / Legal": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Legal", "Politics"],
        "applicationgroup": []
    },
    "Pornography": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Pornography/Sexually Explicit"],
        "applicationgroup": []
    },
    "Real Estate": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Real Estate"],
        "applicationgroup": []
    },
    "Remote Administration": {
        "type": "app-url-category",
        "l7_category": ["Remote access"],
        "url_category": [],
        "applicationgroup": []
    },
    "Restaurants / Dining / Foods": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Restaurants & Dining"],
        "applicationgroup": []
    },
    "Religion": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Religion"],
        "applicationgroup": []
    },
    "Sex": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Gay, Lesbian or Bisexual", "Nudity", "Pornography/Sexually Explicit"],
        "applicationgroup": []
    },
    "Sex Education": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Sex Education"],
        "applicationgroup": []
    },
    "Search Engines / Portals": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Search Engines & Portals"],
        "applicationgroup": []
    },
    "Shopping": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Shopping"],
        "applicationgroup": []
    },
    "Social Networking": {
        "type": "app-url-category",
        "l7_category": ["Social networking"],
        "url_category": ["Social Networking"],
        "applicationgroup": []
    },
    "Software Downloads": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Download Sites"],
        "applicationgroup": []
    },
    "Software Update": {
        "type": "app-url-category",
        "l7_category": ["Software update"],
        "url_category": ["Updates"],
        "applicationgroup": []
    },
    "Spam": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Spam Sites"],
        "applicationgroup": []
    },
    "Sports": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Sports"],
        "applicationgroup": []
    },
    "Spyware / Malicious Sites": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Compromised", "Phishing & Fraud", "Malware"],
        "applicationgroup": []
    },
    "Stealth Tactics": {
        "type": "app-url-category",
        "l7_category": ["Trojan Horses"],
        "url_category": ["Malware"],
        "applicationgroup": []
    },
    "Suspicious Content": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Tasteless", "Phishing & Fraud", "Compromised", "Spam Sites", "Malware"],
        "applicationgroup": []
    },
    "Tasteless": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Tasteless"],
        "applicationgroup": []
    },
    "Translation": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Translators"],
        "applicationgroup": []
    },
    "Travel": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Travel"],
        "applicationgroup": []
    },
    "Vehicles": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Transportation"],
        "applicationgroup": []
    },
    "Video Conferencing": {
        "type": "app-url-category",
        "l7_category": ["Conferencing"],
        "url_category": [],
        "applicationgroup": []
    },
    "Violence": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Violence"],
        "applicationgroup": []
    },
    "VoIP": {
        "type": "app-url-category",
        "l7_category": ["VOIP"],
        "url_category": [],
        "applicationgroup": []
    },
    "Weapons": {
        "type": "app-url-category",
        "l7_category": [],
        "url_category": ["Weapons"],
        "applicationgroup": []
    },
    "Web Conferencing": {
        "type": "app-url-category",
        "l7_category": ["Conferencing"],
        "url_category": [],
        "applicationgroup": []
    },
    "Web Services Provider": {
        "type": "app-url-category",
        "l7_category": ["Web browsing"],
        "url_category": [],
        "applicationgroup": []
    }
}

unknown_cp_app_categoty = {
    "Browser Plugin": None,
    "Browser Toolbar": None,
    "Check Point Products": None,
    "Facebook Business": None,
    "Facebook Education": None,
    "Facebook Entertainment": None,
    "Facebook Friends & Family": None,
    "Facebook Games": None,
    "Facebook Lifestyle": None,
    "Facebook Sports": None,
    "Facebook Utilities": None,
    "Facebook Widgets": None,
    "Friendster Widgets": None,
    "Google Plus Widgets": None,
    "IPTV": None,
    "LinkedIn Widgets": None,
    "MySpace Widgets": None,
    "Ning.com Widgets": None,
    "SMS Tools": None,
    "Social Plugins": None,
    "Web Content Aggregators": None,
    "Web Advertisements": None,
    "Web Browser Acceleration": None,
    "Web Spider": None,
}

url_categories = {
    "Advertisements & Pop-Ups": 1,                      # Реклама и всплывающие окна
    "Alcohol & Tobacco": 2,                             # Алкоголь и табак
    "Anonymizers": 3,                                   # Анонимайзеры
    "Arts": 4,                                          # Искусство
    "Botnets": 61,                                      # Ботнеты
    "Business": 5,                                      # Бизнес
    "CDNs": 58,                                         # CDN
    "Chat": 7,                                          # Чаты
    "Chat-bot AI": 85,                                  # Чат-боты искусственного интеллекта
    "Child Abuse Images": 78,                           # Изображения жестокого обращения с детьми
    "Compromised": 10,                                  # Заражённые сайты
    "Computers & Technology": 11,                       # Компьютеры и технологии
    "Criminal Activity": 12,                            # Преступная деятельность
    "Cryptocurrency Mining": 66,                        # Криптомайнеры
    "Cults": 62,                                        # Регилиозные культы
    "Dating & Personals": 13,                           # Сайты знакомств
    "Download Sites": 14,                               # Douwload-архивы
    "Education": 15,                                    # Образование
    "Entertainment": 16,                                # Развлечения
    "Fashion & Beauty": 63,                             # Мода и красота
    "Finance": 17,                                      # Финансы
    "Forums & Newsgroups": 9,                           # Форумы и новостные ленты
    "Gambling": 18,                                     # Азартные игры
    "Games": 19,                                        # Игры
    "Gay, Lesbian or Bisexual": 79,                     # Нетрадиционная сексуальная ориентация
    "General": 49,                                      # Общие
    "Government": 20,                                   # Правительство
    "Greeting cards": 64,                               # Поздравительные открытки
    "Hacking": 65,                                      # Хакерство
    "Hate & Intolerance": 21,                           # Ненависть и нетерпимость
    "Health & Medicine": 22,                            # Здоровье и медицина
    "Illegal Drug": 23,                                 # Наркотики
    "Illegal Software": 67,                             # Нелегальное ПО
    "Image Sharing": 68,                                # Обмен картинками
    "Information Security": 69,                         # Информационная безопасность
    "Instant Messaging": 70,                            # Сервисы мгновенных сообщений
    "Job Search": 24,                                   # Поиск работы
    "Kids sites": 8,                                    # Детские сайты
    "Legal": 52,                                        # Юриспруденция
    "Leisure & Recreation": 50,                         # Отдых и оздоровление
    "Literature & Books": 80,                           # Литература и книги
    "Local Information": 53,                            # Местные достопримечательность
    "Malware": 42,                                      # Вредоносное ПО
    "Military": 25,                                     # Военные сайты
    "Network Errors": 71,                               # Сетевые ошибки
    "News": 27,                                         # Новости
    "Non-profits & NGOs": 28,                           # Некоммерческие и неправительственные организации
    "Nudity": 29,                                       # Нудизм
    "Nutrition & Diet": 81,                             # Здоровое питание и диеты
    "Online training and tools": 51,                    # Онлайн обучение
    "Parked Domains": 72,                               # Паркованные домены
    "Peer-to-Peer": 73,                                 # Пиринговые сети
    "Personal Sites": 30,                               # Персональные сайты
    "Personal Storage": 57,                             # Персональные хранилища
    "Pets & Animals": 82,                               # Домашние животные
    "Phishing & Fraud": 31,                             # Фишинг и мошенничество
    "Politics": 32,                                     # Политика
    "Pornography/Sexually Explicit": 33,                # Порнография и насилие
    "Private IP Addresses": 74,                         # Частные IP-адреса
    "Profanity": 59,                                    # Нецензурная лексика
    "Professional social networks": 60,                 # Профессиональные социальные сети
    "Real Estate": 34,                                  # Недвижимость
    "Reference and Research": 54,                       # Справочная информация
    "Religion": 35,                                     # Религия
    "Reputation: Low risk": 97,
    "Reputation: Medium risk": 98,
    "Reputation: High risk": 99,
    "Restaurants & Dining": 36,                         # Рестораны и еда
    "School Cheating": 75,                              # Школьные мошенничества
    "Search Engines & Portals": 37,                     # Поисковые системы и порталы
    "Sex Education": 76,                                # Половое воспитание
    "Shopping": 38,                                     # Покупки
    "Social Networking": 39,                            # Социальные сети
    "Spam Sites": 40,                                   # Спам-сайты
    "Sports": 41,                                       # Спорт
    "Stock trading": 43,                                # Фондовый рынок
    "Streaming Media & Downloads": 26,                  # Потоковое мультимедиа и загрузки
    "Tasteless": 77,                                    # Сайты сомнительного содержания - ?
    "Technical or business forums and news groups": 55, # Форумы с технической или бизнес информацией
    "Technical information and documentation": 56,      # Техническая информация
    "Translators": 44,                                  # Переводчики
    "Transportation": 6,                                # Транспорт
    "Travel": 45,                                       # Путешествия
    "Violence": 46,                                     # Насилие
    "Unknown": 0,                                       # Неизвестная тематика
    "Updates": 84,                                      # Обновления
    "Weapons": 47,                                      # Оружие
    "Web-based Email": 48,                              # Веб-почта
}

app_compliance = {
    '0bin': ['0bin'],
    '11st': ['11st'],
    '123rf.com': ['123rf.com'],
    '123VPN': ['123VPN'],
    '1337x.to': ['1337x.to'],
    '1C': ['1C'],
    '1C-Connect': ['1C-Connect'],
    '1C-Connect audio': ['1C-Connect audio'],
    '1C-Connect chat': ['1C-Connect chat'],
    '1C-Connect file transfer': ['1C-Connect file transfer'],
    '1C-Connect proxy': ['1C-Connect proxy'],
    '1C-Connect remote access': ['1C-Connect remote access'],
    '1C Enterprise': ['1C', '1C-Connect', '1C-Connect audio', '1C-Connect chat',
                      '1C-Connect file transfer', '1C-Connect proxy', '1C-Connect remote access'],
    '1clickVPN': ['1clickVPN'],
    '1F Mobile': ['1F Mobile'],
    '2ch.hk': ['2ch.hk'],
    '2GIS': ['2GIS'],
    '360.com': ['360.com'],
    '3DNews': ['3DNews'],
    '3DNews - Daily Digital Digest': ['3DNews'],
    '4chan': ['4chan'],
    '4chan & /b/': ['4chan'],
    '4PDA': ['4PDA'],
    '4Shared': ['4Shared'],
    '4shared': ['4Shared'],
    '4shared-download': ['4Shared'],
    '4shared-upload': ['4Shared'],
    '6to4tcp': ['6to4tcp'],
    '6to4udp': ['6to4udp'],
    '78.ru': ['78.ru'],
    '8Tracks': ['8tracks'],
    '8tracks': ['8tracks'],
    '99designs': ['99designs'],
    'A Bola': ['A Bola'],
    'ABBYY FineReader': ['ABBYY FineReader'],
    'ABC': ['ABC News'],
    'ABC News': ['ABC News'],
    'About me': ['About me'],
    'ABC.go': ['ABC News'],
    'ABS-CBN': ['ABS-CBN'],
    'Absolute Manage': ['Absolute Manage'],
    'ACADEMIA': ['ACADEMIA'],
    'Academia.edu': ['ACADEMIA'],
    'AccuWeather': ['AccuWeather'],
    'accuweather': ['AccuWeather'],
    'Acronis': ['Acronis'],
    'Acronis Snap Deploy': ['Acronis'],
    'Acronis TrueImage': ['Acronis'],
    'ACS': ['ACS'],
    'adaranth': ['adaranth'],
    'ADDP': ['ADDP'],
    'AdGuard': ['AdGuard'],
    'AdNet': ['AdNet'],
    'Adobe': ['Adobe'],
    'Adobe_Com': ['Adobe'],
    'Adobe Connect': ['Adobe'],
    'Adobe Connect-meeting': ['Adobe'],
    'Adobe Connect-meeting-file sharing': ['Adobe'],
    'Adobe Connect-meeting-remote control': ['Adobe'],
    'Adobe Connect-meeting-screen sharing': ['Adobe'],
    'Adobe Creative Cloud': ['Adobe'],
    'Adobe Document Cloud': ['Adobe'],
    'Adobe Update': ['Adobe Update'],
    'ADP': ['ADP'],
    'ADrive': ['Adrive'],
    'Adrive': ['Adrive'],
    'Adventure Island': ['Adventure Island'],
    'AeroAdmin': ['Aeroadmin'],
    'Aeroadmin': ['Aeroadmin'],
    'Aeroflot': ['Aeroflot'],
    'Afaria': ['Afaria'],
    'AFP': ['AFP'],
    'Afreeca': ['AfreecaTV'],
    'AfreecaTV': ['AfreecaTV'],
    'AFS': ['AFS'],
    'Agoda': ['Agoda'],
    'AIM': ['AIM'],
    'AIM Express': ['AIM'],
    'AIM_Express': ['AIM'],
    'AIM_Express_FileTransfer': ['AIM'],
    'AIM-audio chat': ['AIM'],
    'AIM-video chat': ['AIM'],
    'Aion': ['Aion'],
    'AION': ['Aion'],
    'AirBNB': ['AirBNB'],
    'Airbnb': ['AirBNB'],
    'AirDroid': ['AirDroid'],
    'Ali IM': ['Ali IM'],
    'AliTalk IM': ['Ali IM'],
    'AliTalk VoIP': ['Ali IM'],
    'Alibaba': ['Alibaba'],
    'AliExpress': ['AliExpress'],
    'Allods Online': ['Allods Online'],
    'Alpemix': ['Alpemix'],
    'Altiris': ['Altiris'],
    'Amazon': ['Amazon'],
    'AmazonS3': ['Amazon'],
    'Amazon Chime': ['Amazon Chime'],
    'Amazon Chime audio': ['Amazon Chime audio'],
    'Amazon Chime chat': ['Amazon Chime chat'],
    'Amazon Chime desktop sharing': ['Amazon Chime desktop sharing'],
    'Amazon Chime upload/download': ['Amazon Chime upload/download'],
    'Amazon Chime video': ['Amazon Chime video'],
    'AmazonPrimeVideo': ['AmazonPrimeVideo'],
    'Amazon Prime Video': ['AmazonPrimeVideo'],
    'Amazon S3': ['Amazon'],
    'Amazon Web Services (AWS)': ['Amazon'],
    'Ameblo': ['Ameblo'],
    'Amediateka': ['Amediateka'],
    "American Airlines": ['American Airlines'],
    'American Express': ['American Express'],
    'americanexpress': ['American Express'],
    'Americanas': ['Americanas'],
    'AmericanNinjaWarriorNation': ['AmericanNinjaWarriorNation'],
    'Ammyy Admin': ['Ammyy Admin'],
    'Ammy Admin': ['Ammyy Admin'],
    'amo': ['amo'],
    'Among Us': ['Among Us'],
    'AMQP': ['AMQP'],
    'Anatomic P2P': ['BitTorrent announce'],
    'AndroVPN': ['AndroVPN'],
    'aNobii': ['aNobii'],
    'Anonymox': ['Anonymox'],
    "AnonyTun": ['AnonyTun'],
    'Anonytun VPN': ['AnonyTun'],
    'ANts P2P': ['ANts P2P'],
    'Ants P2P': ['ANts P2P'],
    'AntsP2P': ['ANts P2P'],
    'Any.do': ['Any.do'],
    'AnyDesk': ['AnyDesk'],
    'Anyplace Control': ['Anyplace Control'],
    'Anyplace Control P2P': ['Anyplace Control P2P'],
    'Anzu Control': ['Anzu Control'],
    'AOL Mail': ['AOL Mail'],
    'AOL_Webmail': ['AOL Mail'],
    'AOL_Video': ['AIM'],
    'Apache Cassandra': ['Apache Cassandra'],
    'Apache Kafka': ['Apache Kafka'],
    'Aparat': ['Aparat'],
    'Apartments': ['Apartments'],
    'APC PowerChute': ['APC PowerChute'],
    'Apple': ['Apple'],
    'Apple AirPlay': ['Apple AirPlay'],
    'Apple Daily': ['Apple Daily'],
    'Apple Daily mobile': ['Apple Daily mobile'],
    'Apple Daily-video': ['Apple Daily'],
    'Apple Media': ['Apple Media'],
    'Apptivo CRM': ['Apptivo CRM'],
    'Archive of Our Own': ['Archive of Our Own'],
    'Archive.org': ['Archive.org'],
    'Arcserve': ['Arcserve'],
    'ARCserve Backup': ['Arcserve'],
    'Arctic Torrent': ['BitTorrent', 'BitTorrent announce', 'BitTorrent Scrape'],
    'Ares': ['Ares'],
    'Arescadon': ['Arescadon'],
    'ArtStation': ['ArtStation'],
    'ArXiv': ['ArXiv'],
    'Asahi': ['Asahi'],
    'Asana': ['Asana'],
    'ASKfm': ['ASKfm'],
    'ASmallWorld': ['ASmallWorld'],
    'aSmallWorld': ['ASmallWorld'],
    'ASOS': ['ASOS'],
    'Assistant': ['Assistant'],
    'AT&T': ['AT&T'],
    'ATLAS': ['ATLAS'],
    'Atlas VPN': ['Atlas VPN'],
    'Atlassian': ['Atlassian'],
    'Aurora Airlines': ['Aurora Airlines'],
    'AURORA WORLD': ['AURORA WORLD'],
    'Australian Broadcasting Corporation': ['Australian Broadcasting Corporation'],
    'AVA': ['AVA'],
    'EMC Avamar': ['Avamar'],
    'Avamar': ['Avamar'],
    'Avast': ['Avast'],
    'avast! Antivirus': ['Avast'],
    'Avast Secure DNS': ['Avast Secure DNS'],
    'Avast Update': ['Avast Update'],
    'avast! Antivirus-update': ['Avast Update'],
    'Avaya': ['Avaya'],
    'Avira Phantom': ['Avira Phantom'],
    'Avira Phantom VPN': ['Avira Phantom'],
    'Avira Update': ['Avira Update'],
    'Avira Antivir-update': ['Avira Update'],
    'Avito': ['Avito'],
    'Avocent': ['Avocent'],
    'AxiFile': ['AxiFile'],
    'Azur Air': ['Azur Air'],
    'Azure Visual Studio': ['Visual Studio'],
    'B&H Photo-Video': ['B&H Photo-Video'],
    'BackWeb': ['BackWeb'],
    'BACnet': ['BACnet'],
    'BACHNet Protocol (Building Automation and Control Networks)': ['BACnet'],
    'Badongo': ['Badongo'],
    'Badoo': ['Badoo'],
    'Baidu Hi': ['Baidu Hi'],
    'Baidu Player': ['Baidu Player'],
    'Baidu Hi-video chat': ['Baidu Hi'],
    'Baidu Video Search': ['Baidu Player'],
    'Bandcamp': ['Bandcamp'],
    'Banggood': ['Banggood'],
    'BAOFENG': ['BAOFENG'],
    'Baofeng': ['BAOFENG'],
    'Barracuda Backup': ['Barracuda Backup'],
    'Basecamp': ['Basecamp'],
    'BattleField': ['Battle.net'],
    'Battle.Net': ['Battle.net'],
    'Battle.net': ['Battle.net'],
    'BBC': ['BBC'],
    'Bearlo Cloud': ['Bearlo Cloud'],
    'BeePassVPN': ['BeePassVPN'],
    'Benzinga': ['Benzinga'],
    'BestVPNSSH': ['BestVPNSSH'],
    'bet365': ['Bet365'],
    'Bet365': ['Bet365'],
    'Beytoote': ['Beytoote'],
    'BGP': ['BGP (Border Gateway Protocol)'],
    'BGP Protocol': ['BGP (Border Gateway Protocol)'],
    'BGP (Border Gateway Protocol)': ['BGP (Border Gateway Protocol)'],
    'BigBlueButton': ['BigBlueButton'],
    'BigBrother': ['BigBrother'],
    'BigMama VPN': ['BigMama VPN'],
    'BILD.de': ['BILD.de'],
    'BillDesk': ['BillDesk'],
    'Binance': ['Binance'],
    'Bing': ['Bing'],
    'BioBioChile': ['BioBioChile'],
    'Bitbucket': ['Bitbucket'],
    'Bitbucket-download': ['Bitbucket'],
    'Bitbucket-upload': ['Bitbucket'],
    'Bitcasa': ['Bitcasa'],
    'Bitcoin': ['Bitcoin Core and Bitcoin Knots'],
    'Bitcoin Core and Bitcoin Knots': ['Bitcoin Core and Bitcoin Knots'],
    'BitComet': ['BitComet'],
    'Bither': ['Bither'],
    'Bitly': ['Bitly'],
    'Bitrix': ['Bitrix24'],
    'Bitrix24': ['Bitrix24'],
    'Bitshare': ['BitShares'],
    'BitShares': ['BitShares'],
    'BitTorrent': ['BitTorrent'],
    'BitTorrent announce': ['BitTorrent announce'],
    'BitTorrent Scrape': ['BitTorrent Scrape'],
    'BitTorrent Protocol': ['BitTorrent', 'BitTorrent announce', 'BitTorrent Scrape'],
    'BitTorrent Sync': ['BitTorrent', 'BitTorrent announce', 'BitTorrent Scrape'],
    'BitTorrent Now': ['BitTorrent', 'BitTorrent announce', 'BitTorrent Scrape'],
    'BitTornado': ['BitTorrent', 'BitTorrent announce', 'BitTorrent Scrape'],
    'BitTyrant': ['BitTorrent', 'BitTorrent announce', 'BitTorrent Scrape'],
    'BitVPN': ['BitVPN'],
    'BitWise': ['BitWise'],
    'BlackBerry': ['BlackBerry'],
    'Blackboard': ['Blackboard'],
    'Blackboard Chat': ['Blackboard Chat'],
    'BlackPlanet': ['BlackPlanet'],
    'Bleacher Report': ['Bleacher Report'],
    'Blizko': ['Blizko'],
    'Blog Me!': ['Blog Me!'],
    'Blogger': ['Blogger'],
    'Blondie Shop': ['Blondie Shop'],
    'Bloomberg': ['Bloomberg'],
    'Bloomberg professional': ['Bloomberg Professional'],
    'Bloomberg Professional': ['Bloomberg Professional'],
    'BlueCoat': ['BlueCoat'],
    'BOL': ['BOL'],
    'bonpoo': ['Bonpoo'],
    'Bonpoo': ['Bonpoo'],
    'Booking': ['Booking'],
    'Booking.com': ['Booking'],
    'BookMyShow': ['BookMyShow'],
    'BOOM': ['BOOM'],
    'bootsnipp': ['bootsnipp'],
    'Bopup Messenger': ['BopUp Messenger'],
    'BopUp Messenger': ['BopUp Messenger'],
    'Box': ['Box'],
    'Britannica': ['Britannica'],
    'BrowVPN': ['BrowVPN'],
    'Browsec': ['Browsec'],
    'Bubble Fighter': ['Bubble Fighter'],
    'Bukalapak': ['Bukalapak'],
    'Bisiness Insider': ['Bisiness Insider'],
    'Busuu': ['Busuu'],
    'BuzzFeed': ['BuzzFeed'],
    'Byread': ['Byread'],
    'ByShell': ['ByShell'],
    'Ca Sdm': ['Ca Sdm'],
    'CafeMom': ['CafeMom'],
    'Caihong': ['Caihong QQ'],
    'Caihong QQ': ['Caihong QQ'],
    'Caihong-audio-video': ['Caihong QQ'],
    'Caixa.gov.br': ['Caixa.gov.br'],
    'CallOffice': ['CallOffice'],
    'Camfrog': ['Camfrog'],
    'CamFrog_IM': ['Camfrog'],
    'CamFrog_VChat': ['Camfrog'],
    'Camfrog Video Chat': ['Camfrog'],
    'Canon BJNP': ['Canon BJNP'],
    'CANON BJNP Protocol': ['Canon BJNP'],
    'Canva': ['Canva'],
    'Capital One': ['Capital One'],
    'Capitalone': ['Capital One'],
    'CapitalBridge': ['CapitalBridge'],
    'CBS-video': ['Viacom CBS'],
    'CC-Link IE Field Basic': ['CC-Link IE Field Basic'],
    'CCB': ['CCB'],
    'CCTV': ['CCTV'],
    'CCTV Media': ['CCTV Media'],
    'Cdiscount': ['Cdiscount'],
    'cDiscount': ['Cdiscount'],
    'Centurion': ['Centurion'],
    'Championat': ['Championat'],
    'Chase': ['Chase'],
    'Chatango': ['Chatango'],
    'ChatWork': ['ChatWork desktop', 'ChatWork web'],
    'ChatWork desktop': ['ChatWork desktop'],
    'ChatWork web': ['ChatWork web'],
    'Checkvist': ['Checkvist'],
    'Chegg': ['Chegg'],
    'Chess.com': ['Chess.com'],
    'Chewy': ['Chewy'],
    'Chikka': ['Chikka'],
    'Chikka-messenger': ['Chikka'],
    'Chikka_PC': ['Chikka'],
    'Chrome Remote Desktop': ['Chrome Remote Desktop'],
    'Cian': ['Cian'],
    'Cifco Futures': ['Cifco Futures'],
    'Cisco': ['Cisco'],
    'Cisco AnyConnect': ['Cisco'],
    'Cisco WebEx Meetings': ['WebEx'],
    'Cisco WebEx Meetings-Remote Control': ['WebEx'],
    'Cisco WebEx Meetings-file sharing': ['WebEx file sharing'],
    'Cisco WebEx Meetings-file transfer': ['WebEx file sharing'],
    'Citibank': ['Citibank'],
    'Citilink': ['Citilink'],
    'Citrix': ['Citrix'],
    'Citrix Jedi': ['Citrix Jedi'],
    'Citrix JEDI protocol': ['Citrix Jedi'],
    'Citrix ShareFile': ['Citrix ShareFile'],
    'Citrix Systems': ['Citrix Systems'],
    'Citrix Systems HTTP': ['Citrix Systems HTTP'],
    'Classmates': ['Classmates'],
    'Clcikhouse': ['Clcikhouse'],
    'ClickMeeting': ['ClickMeeting'],
    'ClickMeeting file sharing': ['ClickMeeting file sharing'],
    'ClickView': ['ClickView'],
    'Cloob': ['Cloob'],
    'CNN': ['CNN'],
    'CNN-video': ['CNN'],
    'CODESYS': ['CodeSys'],
    'CommFort': ['CommFort'],
    'Commvault': ['Commvault'],
    'Component Network over IP (CN/IP)': ['Component Network over IP (CN/IP) (CEA 852)'],
    'Concur': ['Concur Solutions'],
    'Convo': ['Convo'],
    'Coupang': ['Coupang'],
    'Craigslist': ['Craigslist'],
    'Crashplan': ['CrashPlan'],
    'CrossLoop': ['CrossLoop'],
    'CrossFire': ['CrossFire'],
    'Ctdisk': ['ctdisk.com'],
    'CVS': ['CVS'],
    'CVSup': ['CVSup'],
    'CyberGhost': ['CyberGhost VPN'],
    'CyberGhost VPN': ['CyberGhost VPN'],
    'Cyndicate': ['Cyndicate'],
    'DailyMotion': ['Dailymotion'],
    'Daum': ['Daum'],
    'Daum tvpot': ['Daum MyPeople'],
    'Daum_Web': ['Daum', 'Daum MyPeople', 'Daum Touch'],
    'DB2': ['DB2'],
    'DCE-RPC Protocol': ['DCERPC'],
    'DCE_RPC Protocol': ['DCERPC'],
    'Dcinside': ['dcinside'],
    'Deezer': ['Deezer'],
    'Degoo': ['Degoo'],
    'Dell-DRAC': ['Dell DRAC'],
    'Deposit Files': ['DepositFiles'],
    "Desknet's": ['desknets'],
    'desknets': ['desknets'],
    'Detik': ['Detik'],
    'DeviantArt': ['DeviantArt'],
    'DHCP': ['DHCP'],
    'DHCP Protocol': ['DHCP'],
    'Diablo': ['Diablo III'],
    'DIAMETER': ['DIAMETER'],
    'Diameter': ['DIAMETER'],
    'Diameter Protocol': ['DIAMETER'],
    'Dictionary.com': ['Dictionary'],
    'Digg': ['Digg'],
    'Digsby': ['Digsby Beta'],
    'Diino': ['Diino'],
    'Direct Connect': ['DC Protocol'],
    'DirectConnect': ['DC Protocol'],
    'Discord': ['DiscordApp'],
    'distcc': ['distcc'],
    'DivShare': ['DivShare'],
    'Divshare': ['DivShare'],
    'Dl_Free': ['Dl.Free'],
    'DLMS/COSEM(IEC62056)': ['DLMS/COSEM'],
    'DNP3': ['DNP3'],
    'DNP3 Protocol': ['DNP3'],
    'DNS': ['DNS'],
    'DNS Protocol': ['DNS'],
    'DNSCrypt': ['DNSCrypt'],
    'Docstoc': ['Docstoc'],
    'Doctor Web AntiVirus': ['Dr Web Update'],
    'DocuSign': ['DocuSign'],
    'Doodle-download': ['Doodle'],
    'DotVPN': ['DotVPN'],
    'DragonNest': ['Dragon Nest'],
    'Draugiem': ['Draugiem'],
    'Dreamstime': ['DreamsTime'],
    'DroidVPN': ['DroidVPN'],
    'Dropbox': ['DropBox'],
    'Dropbox Lan Sync Protocol': ['Dropbox Lan Sync Protocol'],
    'Dropbox paper': ['Dropbox Lan Sync Protocol'],
    'Dropbox-web': ['Dropbox Web Download', 'Dropbox Web Upload'],
    'Dropbox-web download': ['Dropbox Web Download'],
    'Dropbox-web upload': ['Dropbox Web Upload'],
    'Dropmefiles': ['DropMeFiles.com'],
    'Dropmefiles-download': ['DropMeFiles.com'],
    'Dropmefiles-upload': ['DropMeFiles.com'],
    'DropSend': ['DropSend'],
    'Duolingo': ['Duolingo'],
    'Earthcam': ['EarthCam'],
    'earthcam': ['EarthCam'],
    'Easyprojects': ['Easyprojects'],
    'eBuddy': ['eBuddy'],
    'Ebuddy': ['eBuddy'],
    'Ebuddy_Mobile': ['eBuddy for Android'],
    'eDonkey_eMule': ['eMule'],
    'eFriend': ['eFriend'],
    'Effusia': ['Effusia Business Messenger'],
    'Egnyte': ['Egnyte'],
    'eHarmony': ['eHarmony'],
    'ELCOM 90 protocol': ['Elcom'],
    'EMC NetWorker': ['EMC NetWorker'],
    'eMule': ['eMule'],
    'Enchant': ['Enchant'],
    'EndNote': ['EndNote'],
    'Epic Browser': ['Epic Browser VPN'],
    'Epicurious': ['Epicurious'],
    'Epicurious-video': ['Epicurious'],
    'ESET': ['ESET NOD32 update'],
    'ESPN Player': ['ESPN'],
    'ESPN SportCenter': ['ESPN'],
    'ESPN Player-streaming': ['ESPN'],
    'Ether S Bus Protocol': ['Ether-S-Bus'],
    'Ether S I/O Protocol': ['Ether-S-I/O'],
    'EtherNet/IP': ['EtherNet/IP'],
    'Etsy': ['Etsy'],
    'Eventbrite': ['Eventbrite'],
    'Evernote': ['Evernote'],
    'Evernote-download': ['Evernote'],
    'Evernote-upload': ['Evernote'],
    'Evernote-sharing': ['Evernote'],
    'Evernote-posting': ['Evernote'],
    'Evernote-editing': ['Evernote'],
    'Facebook': ['Facebook'],
    'Facebook Apps': ['Facebook Apps'],
    'Facebook_Applications': ['Facebook Apps'],
    'Facebook Chat': ['Facebook  Chat'],
    'Facebook-chat': ['Facebook  Chat'],
    'Facebook Games': ['Facebook Apps'],
    'Facebook_Games': ['Facebook Apps'],
    'Facebook Groups': ['Facebook'],
    'Facebook_Login': ['Facebook'],
    'Facebook Messenger': ['Facebook  Chat'],
    'Facebook_Messenger': ['Facebook  Chat', 'Facebook Video'],
    'Facebook_Messages': ['Facebook  Chat'],
    'Facebook-posting': ['Facebook'],
    'Facebook_Posting': ['Facebook  Chat', 'Facebook Upload'],
    'Facebook Social Plugins': ['Facebook Apps'],
    'Facebook Video': ['Facebook Video'],
    'Facebook_Videos': ['Facebook Video'],
    'Facebook_VideoChat': ['Facebook Video', 'Facebook  Chat'],
    'Facebook-video': ['Facebook Video'],
    'Facebook-video-upload': ['Facebook Video', 'Facebook Upload'],
    'Facebook Upload': ['Facebook Upload'],
    'Facebook_WebBrowsing': ['Facebook', 'Facebook Video', 'Facebook Upload', 'Facebook Apps', 'Facebook  Chat'],
    'Facebook_Photos': ['Facebook Upload', 'Facebook Apps'],
    'Facebook_FileTransfer': ['Facebook Upload'],
    'Fastmail': ['Fastmail'],
    'FastMail': ['Fastmail'],
    'FactSet': ['FactSet'],
    'FastStunnel': ['FastStunnel'],
    'Fasttrack': ['FastTrack'],
    'FC2': ['FC2'],
    'FC2-video': ['FC2'],
    'FC2-video-upload': ['FC2'],
    'FCC Speed Test': ['FCC Speed Test'],
    'Fetion': ['Fetion'],
    'Fetion_IM': ['Fetion'],
    'FetionMobile': ['Fetion'],
    'Fetion_Transfer': ['Fetion'],
    'Fetion_VoIP': ['Fetion'],
    'Fetion-audio-video': ['Fetion'],
    'Fetion-file-transfer': ['Fetion'],
    'File Dropper': ['File Dropper'],
    'FileDropper': ['FileDropper'],
    'FileCatalyst Direct ': ['FileCatalyst'],
    'FileHippo': ['FileHippo'],
    'Fileguri': ['FileGuri'],
    'FileMaker Pro': ['FileMaker Pro'],
    'FilesAnywhere': ['FilesAnywhere'],
    'FilePipe P2P': ['Ares', 'FastTrack', 'Gnutella'],
    'FineVPN-services': ['Fine VPN'],
    'Firefox': ['Firefox'],
    'FirePhoenix': ['FirePhoenix'],
    'fiverr': ['Fiverr'],
    'FIX': ['FIX (Financial Information eXchange)'],
    'FIX protocol': ['FIX (Financial Information eXchange)'],
    'Flash': ['FlashGet FMS', 'FlashGet DNS', 'FlashGet HTTP', 'FlashGet TCP', 'FlashGet UDP'],
    'FlashGet': ['FlashGet DNS', 'FlashGet HTTP', 'FlashGet TCP', 'FlashGet UDP'],
    'Flickr': ['Flickr'],
    'FlipDrive': ['FlipDrive'],
    'Flixster': ['Flixster Movies'],
    'Flixwagon': ['Flixwagon'],
    'Flixwagon-download': ['Flixwagon Video'],
    'FlyVPN': ['FlyVPN SSL'],
    'FortiClient-update': ['FortiClient Update'],
    'Fotki': ['Fotki'],
    'Foursquare': ['Foursquare'],
    'Free': ['Free VPN'],
    'FreeCast': ['FreeCast'],
    'FreeGate': ['Freegate'],
    'FreeMyBrowser': ['FreeMyBrowser'],
    'Freshdesk': ['Freshdesk'],
    'Freshsales': ['Freshsales'],
    'Frigate': ['Frigate VPN'],
    'FTP': ['FTP'],
    'FTPS': ['ftps'],
    'Fubar': ['fubar.com'],
    'Fuze Meeting': ['Fuze Meeting'],
    'G3 Torrent': ['BitTorrent', 'BitTorrent announce', 'BitTorrent Scrape'],
    'Gadu-Gadu': ['Gadu Gadu'],
    'Gadu_Gadu': ['Gadu Gadu'],
    'GameSpy': ['GameSpy'],
    'Garena': ['Garena'],
    'Garena_Filetransfer': ['Garena'],
    'GatherPlace': ['GatherPlace'],
    'Gbridge': ['gBridge'],
    'gBridge': ['gBridge'],
    'CORBA/GIOP Protocol': ['GIOP Protocol'],
    'GIPHY': ['GIPHY'],
    'Giphy': ['GIPHY'],
    'Gimme P2P': ['Gnutella'],
    'git': ['Github', 'Gitlab', 'Git Smart Protocol'],
    'GitHub': ['Github'],
    'Github': ['Github'],
    'GitHub-download': ['Git Smart Protocol'],
    'GitHub-editing': ['Github', 'Git Smart Protocol'],
    'GitHub-posting': ['Github', 'Git Smart Protocol'],
    'GitHub-upload': ['Git Smart Protocol'],
    'GitLab': ['Gitlab'],
    'Gitlab': ['Gitlab'],
    'GitLab-download': ['Git Smart Protocol'],
    'Gliffy': ['Gliffy'],
    'Gmail': ['Gmail'],
    'GMail': ['Gmail'],
    'Gmarket': ['Gmarket'],
    'GMX': ['GMX'],
    'Gnome Bittorrent': ['BitTorrent', 'BitTorrent announce', 'BitTorrent Scrape'],
    'Gnutella': ['Gnutella'],
    'Gnutella Protocol': ['Gnutella'],
    'Gom VPN': ['Gom VPN'],
    'GoMeetNow': ['GoMeetNow'],
    'GooberMessenger': ['goober Messenger'],
    'GooberMessenger_FileTransfer': ['goober Messenger'],
    'GooberMessenger_Media': ['goober Messenger'],
    'GooberMessenger_SIP': ['goober Messenger'],
    'Goodreads': ['Goodreads'],
    'Google Meet-chat': ['Google Chat'],
    'Google Docs': ['Google Docs'],
    'Google_Docs': ['Google Docs'],
    'Google Drive-web': ['Google Drive'],
    'Google Drive-enterprise': ['Google Drive'],
    'Google_Earth': ['Google Maps'],
    'Google Finance': ['Google Finance'],
    'Google_Finance_Posting': ['Google Finance'],
    'Google Maps': ['Google Maps'],
    'Google Meet': ['Google Meet'],
    'Google Services': ['Google Chat', 'Google Contacts', 'Google Docs', 'Google Drive', 'Google Duo',
                        'Google Finance', 'Google Maps', 'Google Meet'],
    'GoToMeeting/GoToWebinar': ['GoToMeeting app', 'GoToMeeting audio', 'GoToMeeting chat', 'GoToMeeting web'],
    'GoToMeeting/GoToWebinar-file transfer': ['GoToMeeting app'],
    'GoogleTalk_VoIP': ['Google Meet', 'Google Duo'],
    'Google+_VoIP': ['Google Meet', 'Google Duo'],
    'GoogleTalk_IM': ['Google Chat'],
    'GranadoEspada': ['GTanado Espada'],
    'grooveshark': ['GrooveShark'],
    'GuaGua': ['Guagua 2010'],
    'Guardster': ['Guardster'],
    'Gyazo': ['Gyazo'],
    'H.225': ['H.225.0'],
    'H.225.0': ['H.225.0'],
    'H323': ['H323', 'H.323 Gatestat'],
    'H.323': ['H323', 'H.323 Gatestat'],
    'H.323 Protocol': ['H323', 'H.323 Gatestat'],
    'H245': ['H245'],
    'H.245': ['H245'],
    'H245 Protocol': ['H245'],
    'H.245 Protocol': ['H245'],
    'Hadoop': ['HRPC (Hadoop RPC)'],
    'Hart IP': ['HART IP Protocol'],
    'HBO Go': ['HBO Go'],
    'HBO': ['HBO Now'],
    'High Level Data Link Control (HDLC Encapsulation)': ['HDLC-OVER-TCP'],
    'Hide.me': ['Hide.me/vpn-free.pro UDP'],
    'Hideman VPN': ['Hideman VPN'],
    'HideMe VPN': ['HideMe TCP'],
    'Hightail': ['Hightail'],
    'HipChat': ['Hipchat'],
    'Hola': ['Hola VPN'],
    'Hopster': ['Hopster'],
    'Hotsuite': ['Hotsuite'],
    'Hotline': ['Hotline'],
    'Hotline Connect': ['Hotline'],
    'Hotspot': ['Hotspot Shield'],
    'Hotspot Shield': ['Hotspot Shield'],
    'Hoxx VPN': ['Hoxx/Setup VPN'],
    'HTTP': ['HTTP'],
    'HTTP/2': ['HTTP'],
    'HTCondor': ['Condor UDP'],
    'HTTP/2 over TLS': ['HTTPS'],
    'HTTPS': ['HTTPS'],
    'HubSpot': ['HubSpot'],
    'HULFT': ['HULFT'],
    'Hulu': ['Hulu'],
    'HuLu': ['Hulu'],
    'Huntmine': ['HuntMine'],
    'Hyves': ['Hyves chat'],
    'Hyves-chat': ['Hyves chat'],
    'IAX': ['IAX'],
    'IceChat': ['ICE Chat'],
    'iChat': ['iChat'],
    'Ichat': ['iChat'],
    'ICMP': ['Linux ICMP', 'Mac ICMP', 'Win ICMP'],
    'ICQ': ['Web ICQ'],
    'ICQ_IM': ['Web ICQ'],
    'ICQ_VoIP': ['Web ICQ'],
    'IEC 60870-5-104': ['IEC 104'],
    'IEC 60870-5-104 - ( IEC 101 ) Delay Acquistion Command': ['IEC 104 ASDU'],
    'Synchrophasor Protocol (IEEE C37.118)': ['IEEE C37.118 Synchrophasor'],
    'IKE': ['IKE'],
    'IKEv1': ['IKE'],
    'IKEv2': ['IKE'],
    'IKE Protocol': ['IKE'],
    'IMAP': ['IMAP'],
    'IMAP Protocol': ['IMAP'],
    'IMDb': ['IMDb'],
    'imgur': ['Imgur'],
    'IMO': ['IMO IM'],
    'Imo IM': ['IMO IM'],
    'ImoIM': ['IMO IM'],
    'ImoIM_Voip': ['IMO IM'],
    'IMVU': ['IMVU'],
    'Imvu': ['IMVU'],
    'indeed': ['indeed'],
    'Insightly CRM': ['Insightly CRM'],
    'Instagram': ['Instagram'],
    'Instagram-posting': ['Instagram'],
    'Instagram-video': ['Instagram'],
    'Instagram-upload': ['Instagram'],
    'InvisibleNET VPN': ['InvisibleNET'],
    'IPP (Internet Printing Protocol)': ['IPP (Internet Printing Protocol)'],
    'IRC': ['IRC'],
    'IRC Protocol': ['IRC'],
    'iRODS': ['iRODS'],
    'Internet Small Computer System Interface (iSCSI)': ['iSCSI'],
    'IPP': ['IPP (Internet Printing Protocol)'],
    'IPSec': ['ESP', 'IKE'],
    'IPV6_OVER_IPV4': ['6to4tcp', '6to4udp'],
    'ISL Light': ['ISL Light'],
    'Issuu': ['Issuu'],
    'iStock': ['iStock Photo'],
    'Jabber Protocol (XMPP)': ['XMPP'],
    'Jango': ['Jango'],
    'Java Update': ['Java Update Service'],
    'Java_Update': ['Java Update Service'],
    'JAP': ['JonDo/JAP'],
    'Jenkins': ['Jenkins CLI'],
    'Jitsi Meet': ['Jitsi Meet Online'],
    'Jobber': ['Jobber'],
    'JoinMe': ['Join me'],
    'Jottacloud-upload': ['Jottacloud'],
    'Jottacloud-download': ['Jottacloud'],
    'JumboMail': ['JumboMail'],
    'JXTA Protocols': ['JXTA Protocol'],
    'KakaoTalk': ['KakaoTalk chat'],
    'Kanban Tool': ['Kanban Tool'],
    'Kaseya': ['Kaseya'],
    'Kaskus': ['Kaskus'],
    'Kaspersky': ['Kaspersky Update'],
    'Kaspersky Lab-update': ['Kaspersky Update'],
    'Kazaa Media Desktop': ['Kazaa'],
    'Kazaa Lite': ['Kazaa'],
    'Kerberos': ['Kerberos5'],
    'Kerberos Protocol': ['Kerberos5'],
    'Kerika': ['Kerika'],
    'Kickserv': ['Kickserv'],
    'Kik': ['Kik Messenger'],
    'Kingsoft Services': ['Kingsoft'],
    'Knight Online': ['Knight Online'],
    'KNXnet/IP': ['KNXNet/IP'],
    'Kproxy': ['Kproxy'],
    'Last FM': ['Last.fm'],
    'Last_FM': ['Last.fm'],
    'LDAP': ['LDAP'],
    'LDAP Protocol': ['LDAP'],
    'LeBonCoin': ['Leboncoin'],
    'Leboncoin': ['Leboncoin'],
    'Legends': ['League of Legends'],
    'Libero Video': ['Libero'],
    'Lifesize': ['LifeSize'],
    'LINE': ['LINE'],
    'Line_IM': ['LINE'],
    'Line_VoIP': ['LINE'],
    'LinkedIn': ['LinkedIn'],
    'Linkedin': ['LinkedIn'],
    'Linkedin_Link_Twitter_Account': ['LinkedIn'],
    'LiteManager': ['Lite Manager'],
    'live365': ['Live365'],
    'LiveJornal': ['LiveJornal'],
    'Livejornal': ['LiveJornal'],
    'LogMeIn': ['LogMeIn'],
    'LogMeIn rescue': ['LogMeIn login'],
    'LoopcVPN': ['Loopc VPN'],
    'MailRu': ['Mail.ru'],
    'Mail.ru': ['Mail.ru'],
    'Mail.Ru Agent': ['Mail.Ru Agent'],
    'Mail.ru_Agent': ['Mail.Ru Agent'],
    'Mail.ru_Webagent': ['Mail.Ru Agent'],
    'Mail.ru-mail': ['Mail.ru'],
    'Mail.ru_mail': ['Mail.ru'],
    'Mail.Ru Agent-file transfer': ['Mail.ru Cloud'],
    'Mail.ru_Agent_FileTransfer': ['Mail.ru Cloud'],
    'Mail.ru-cloud': ['Mail.ru Cloud'],
    'MailBigFile': ['MailBigFile'],
    'MailChimp': ['MailChimp'],
    'Manolito': ['Manolito'],
    'McAfee': ['McAfee Update'],
    'McAfee-update': ['McAfee Update'],
    'MediaFire': ['MediaFire'],
    'MediaGet': ['MediaGet'],
    'Meetup': ['Meetup'],
    'Mega': ['Mega'],
    'MEGACO': ['MEGACO'],
    'Megaproxy': ['Megaproxy'],
    'Memcached': ['Memcached'],
    'Metacafe': ['Metacafe'],
    'MetaCafe': ['Metacafe'],
    'MGCP': ['MGCP'],
    'MGCP Protocol': ['MGCP'],
    'Microsoft Download Manager': ['Microsoft Update', 'WinUpdate'],
    'Microsoft_Download_Manager': ['Microsoft Update', 'WinUpdate'],
    'Microsoft Edge': ['Edge'],
    'Microsoft Office Groove': ['Groove'],
    'Microsoft OneDrive': ['OneDrive'],
    'Microsoft OneDrive-web': ['OneDrive'],
    'Microsoft Outlook-web': ['Outlook'],
    'Microsoft Outlook-web-file transfer': ['Outlook'],
    'Microsoft Outlook-web-posting': ['Outlook'],
    'Microsoft Media Server (MMS)': ['MS MMS'],
    'Microsoft Teams': ['MS Teams'],
    'Microsoft Teams-download': ['MS Teams File sharing & Chat'],
    'Microsoft Teams-upload': ['MS Teams File sharing & Chat'],
    'Microsoft Teams-editing': ['MS Teams File sharing & Chat'],
    'Microsoft Teams-file transfer': ['MS Teams File sharing & Chat'],
    'Microsoft Teams-sharing': ['MS Teams File sharing & Chat'],
    'Microsoft Teams-posting': ['MS Teams', 'MS Teams File sharing & Chat'],
    'Microsoft Teams-remote control': ['MS Teams', 'MS Teams File sharing & Chat'],
    'Microsoft Teams-sharing': ['MS Teams File sharing & Chat'],
    'Microsoft Teams-Web Tab': ['MS Teams'],
    'Microsoft Store': ['Microsoft Store'],
    'Microsoft SQL Server (TDS Protocol)': ['TDS (Tabular Data Stream)'],
    'Mikogo': ['Mikogo'],
    'MindMeister': ['Mindmeister'],
    'Mindomo': ['Mindomo'],
    'MinerGate': ['MinerGate'],
    'Miro': ['Miro'],
    'MissLee Messenger': ['MissLee'],
    'MoMo': ['Momo IM'],
    'MMS1': ['MMS'],
    'MMS2': ['MMS'],
    'MMS Protocol': ['MMS'],
    'MocoSpace': ['MocoSpace'],
    'Modbus Protocol': ['Modbus'],
    'Monday': ['Monday'],
    'MongoDB': ['MongoDB'],
    'Moo': ['Moo'],
    'MQTT Protocol': ['MQTT'],
    'MS-Netlogon Protocol': ['NETLOGON'],
    'MSN_Game': ['MSN Game'],
    'MSN_VoIP': ['MSN Messenger', 'MSN Shell', 'MSN Video'],
    'MSN_IM': ['MSN Messenger', 'MSN Shell'],
    'MsnShell': ['MSN Shell'],
    'MSN_Transfer': ['MSN file transfer'],
    'MSN-web': ['MSN'],
    'MSN Web Messenger': ['MSN Messenger'],
    'Msn_Webmessenger_IM': ['MSN Messenger'],
    'MSRP': ['MSRP'],
    'MTConnect': ['MTConnect Protocol'],
    'Munin': ['Munin'],
    'Mute': ['Mute'],
    'MyAnimeList': ['MyAnimeList'],
    'My-Files.RU': ['My-Files'],
    'MyGreenPC': ['MyGreenPC'],
    'MySpace': ['MySpaceIM'],
    'MySpace Video': ['MySpaceIM'],
    'MySpaceIM': ['MySpaceIM'],
    'MySQL': ['MySQL'],
    'MySQL Community Server': ['MySQL'],
    'NASA': ['NASA'],
    'NateOn': ['NateOn'],
    'NateOn-audio video': ['NateOn', 'NateOn VOIP'],
    'Nate-video': ['NateOn', 'NateOn VOIP'],
    'Naver': ['Naver'],
    'NBA.com-video': ['NBA', 'NBA Turner'],
    'NBA_TOM': ['NBA', 'NBA Turner'],
    'NBC': ['NBC News'],
    'NBC News': ['NBC News'],
    'NBC-video': ['NBC News'],
    'Netease_DiskWeb': ['Netease'],
    'Netease Webdisk': ['Netease'],
    'Netflix': ['Netflix'],
    'Netload': ['NETLOAD'],
    'Nexonia': ['Nexonia'],
    'NewEgg': ['Newegg'],
    'NFS': ['NFS'],
    'NFS Protocol': ['NFS'],
    'Ngrok': ['Ngrok'],
    'NicoVideo': ['Nicovideo'],
    'Nimbuzz': ['Nimbuzz Messenger'],
    'Novell Filr': ['Novell Filr'],
    'NNTP': ['NNTP'],
    'NTP': ['NTPv3', 'NTPv4'],
    'NTP Protocol': ['NTPv3', 'NTPv4'],
    'NS_4Shared_Download': ['4Shared'],
    'NS_Depositfiles_Download': ['DepositFiles'],
    'NS_FileFactory_Dounload': ['FileFactory'],
    'NYTimes': ['NYTimes'],
    'OCSP': ['OCSP'],
    'Odnoklassniki': ['Odnoklassniki'],
    'Odnoklassniki-apps': ['Odnoklassniki'],
    'Odnoklassniki-messaging': ['Odnoklassniki'],
    'Odnoklassniki_messaging': ['Odnoklassniki'],
    'Odnoklassniki-voice-video chat': ['Odnoklassniki'],
    'Office365-Outlook': ['Office365'],
    'Office365-Outlook-web': ['Office365'],
    'OkCupid': ['OkCupid'],
    'Okezone': ['Okezone'],
    'Omegle': ['Omegle'],
    'Omron FINS protocol': ['Omron Fins UDP'],
    'OnePageCRM': ['OnePageCRM'],
    'ooVoo': ['ooVoo'],
    'OoVoo_IM': ['ooVoo'],
    'OoVoo_VoIP': ['ooVoo'],
    'OPC Unified Architecture': ['OPC UA'],
    'OPC DA': ['OPC DA'],
    'OpenDrive': ['OpenDrive'],
    'OpenVPN': ['OpenVPN tcp', 'OpenVPN udp'],
    'Opera VPN': ['Opera VPN'],
    'Oracle': ['Oracle'],
    'Origin': ['Origin'],
    'Outbrain': ['Outbrain'],
    'Outlook Web Access': ['Outlook'],
    'P2Ptv Remote Control': ['TVU'],
    'PacketiX': ['PacketiX'],
    'PacketiX VPN': ['PacketiX'],
    'PageKite': ['PageKite'],
    'Palringo': ['Palringo'],
    'Palringo Rich Messaging': ['Palringo'],
    'Paltalk': ['Paltalk'],
    'Paltalk_IM': ['Paltalk'],
    'Paltalk_VoIP': ['Paltalk'],
    'Panda': ['Panda update'],
    'PANDA Security-update': ['Panda update'],
    'Pandora Mobile': ['Pandora'],
    'PandoraTV': ['Pandora'],
    'Pandora Radio': ['Pandora'],
    'PandoraRadio': ['Pandora'],
    'Pantheon': ['Pantheon'],
    'Pastebin': ['Pastebin'],
    'PayPal': ['PayPal'],
    'pcAnywhere': ['pcAnywhere'],
    'pCloud': ['pCloud'],
    'PCoIP': ['PCoIP'],
    'Perforce': ['Perforce'],
    'Periscope': ['Periscope'],
    'Photobucket': ['Photobucket'],
    'Pic Collage': ['Pic Collage'],
    'Pichat': ['Pichat'],
    'Pinterest': ['Pinterest'],
    'Pipedrive': ['Pipedrive'],
    'Pivotal Tracker': ['Pivotal Tracker'],
    'Podio': ['Podio'],
    'POP3': ['POP3'],
    'POP3 Protocol': ['POP3'],
    'PostgreSQL': ['PostgreSQL'],
    'PostgreSQL Protocol': ['PostgreSQL'],
    'PPlive': ['PPlive'],
    'PPTP Protocol': ['PPTP'],
    'Prezi': ['Prezi'],
    'Privatix': ['Privatix'],
    'Profinet Protocol': ['Profinet IO over DCERPC'],
    'ProofHub': ['ProofHub'],
    'ProtonMail': ['ProtonMail'],
    'ProWorkflow': ['ProWorkflow'],
    'ProxyLocal': ['ProxyLocal'],
    'ProxySite': ['Proxysite'],
    'PureVPN': ['purevpn'],
    'PutLocker': ['Putlocker'],
    'Qik': ['Qik Video'],
    'Qik-video upload': ['Qik Video'],
    'Qik-video viewing': ['Qik Video'],
    'Qlik': ['Qlik'],
    'Qnext': ['Qnext'],
    'Quake': ['Quake 4'],
    'Quake3 Protocol': ['Quake 4'],
    'Quic Protocol(RFC 9000)': ['QUIC'],
    'Quic Protocol(proprietary)': ['QUIC'],
    'QuickBooks Online': ['QuickBooks'],
    'Quora': ['Quora'],
    'QVOD': ['QVOD', 'Qvod'],
    'Qvod Player': ['QVOD', 'Qvod'],
    'RADIUS': ['Radius'],
    'RADIUS Protocol': ['Radius'],
    'Radmin': ['Radmin'],
    'Raketu': ['Raketu'],
    'Rambler': ['Rambler'],
    'Rapidgator.net': ['RAPIDGATOR'],
    'Rapidshare': ['RapidShare'],
    'RaviShare': ['Ravishare'],
    'Raynet': ['Raynet'],
    'Razor': ['Razor'],
    'Rdio': ['Rdio'],
    'RDP': ['RDP'],
    'ReadyTalk': ['ReadyTalk'],
    'RealPlayer': ['RealPlayer'],
    'RealtimeBoard': ['RealtimeBoard'],
    'Realtor': ['Realtor.com'],
    'Reddit': ['Reddit'],
    'Redis': ['Redis'],
    'ResearchGate': ['ResearchGate'],
    'Reuters': ['Reuters'],
    'Riverbed RiOS': ['Riverbed'],
    'rsync': ['Rsync'],
    'Rsync': ['Rsync'],
    'RTCP': ['RTCP'],
    'RTCP Protocol': ['RTCP'],
    'RTMP': ['RTMP'],
    'RTMP Protocol': ['RTMP'],
    'Real Time Publish Subscribe Protocol (RTPS)': ['RTPS'],
    'RTP': ['RTP'],
    'RTSP': ['RTSP'],
    'RTSP Protocol': ['RTSP'],
    'RPC': ['DCERPC'],
    'RuneScape': ['RuneScape'],
    'Rutube': ['Rutube'],
    'RuTube Media Uploader': ['Rutube'],
    'S7 protocol': ['S7Comm'],
    'S7 Plus Protocol': ['S7Comm Plus'],
    'Saba Centra': ['Saba Centra Meeting'],
    'Salesforce': ['Salesforce'],
    'Salesforce Marketing Cloud': ['Salesforce CRM'],
    'SAP': ['SAP'],
    'SapoVideo': ['SAPO'],
    "SCADA Protocols": ['GE iFix SCADA Systems', 'OpenSCADA'],
    'Scribd': ['Scribd'],
    'Send Anywhere': ['Send Anywhere'],
    'Sendspace': ['SendSpace'],
    'ServiceNow': ['ServiceNow'],
    'SharePoint': ['SharePoint'],
    'SharePoint-online': ['SharePoint'],
    'SharePoint-online-posting': ['SharePoint'],
    'SharePoint-documents': ['SharePoint'],
    'SharePoint - Login failed': ['SharePoint'],
    'SharePoint - Login succeeded': ['SharePoint'],
    'Shazam': ['Shazam'],
    'Shutterstock': ['ShutterStock'],
    'Shutterstock-download': ['ShutterStock'],
    'Shutterstock-upload': ['ShutterStock'],
    'Signal': ['Signal Messenger'],
    'SignEasy': ['SignEasy'],
    'Signiant': ['Signiant'],
    'SimpleHelp': ['SimpleHelp'],
    'Simplite-msn': ['SimpLite MSN'],
    'SinaTV': ['Sina Weibo'],
    'Sina-Weibo': ['Sina Weibo'],
    'SIP': ['SIP'],
    'SIP Protocol': ['SIP'],
    'Skinny Client Control Protocol (SCCP)': ['SCCP'],
    'SkyDrive': ['OneDrive'],
    'Skydur': ['SkyDur'],
    'Skype': ['Skype'],
    'Skype for Business (Lunc)': ['Skype for Business'],
    'Skype for Business (Lunc)-sharing': ['Skype for Business',
                                          'Skype for business desktop sharing',
                                          'Skype for business File Transfer'],
    'Skype for Business (Lunc)-video and voip': ['Skype for Business',
                                                 'Skype for business desktop sharing',
                                                 'Skype for business File Transfer'],
    'Skype - Video Chat': ['Skype Chat', 'Skype Call'],
    'Skype_VoIP': ['Skype', 'Skype screen sharing'],
    'Skype_IM': ['Skype', 'Skype Chat', 'Skype for Business', 'Skype screen sharing'],
    'Slack': ['Slack'],
    'Slack-audio': ['Slack'],
    'Slack-chat': ['Slack'],
    'Slack-download': ['Slack'],
    'Slack-upload': ['Slack'],
    'SlideShare': ['SlideShare'],
    'SlingBox': ['Sling'],
    'Sling TV': ['Sling'],
    'Smallpdf-upload': ['Smallpdf'],
    'Smallpdf-download': ['Smallpdf'],
    'Smartfile': ['SmartFile'],
    'Smartsheet': ['Smartsheet'],
    'SMB': ['SMB', 'SMB2', 'SMBv3'],
    'Server Message Block (SMB)': ['SMB'],
    'Server Message Block v2 (SMBv2)': ['SMB2'],
    'Server Message Block v3 (SMBv3)': ['SMBv3'],
    'SMTP': ['SMTP'],
    'SMTP Protocol': ['SMTP'],
    'SMPP': ['SMPP'],
    'Smugmug': ['SmugMug'],
    'Snapchat': ['Snapchat'],
    'SNMP': ['SNMP v1', 'SNMP v2c', 'SNMP v3'],
    'SNMP Protocol': ['SNMP v1', 'SNMP v2c', 'SNMP v3'],
    'SNMPv3': ['SNMP v3'],
    'SOAP_HTTP': ['SOAP'],
    'Socks5': ['SOCKS5'],
    'Softros LAN Messenger': ['Softros'],
    'Softros_Messenger_FileTransfer': ['Softros'],
    'SogouExplorer': ['SogouMap'],
    'Sogou Map': ['SogouMap'],
    'Sohu': ['Sohu'],
    'Sohu_News': ['Sohu'],
    'SohuTV': ['Sohu'],
    'Sohu video-upload': ['Sohu'],
    'Sohu Weibo': ['Sohu'],
    'Sohu Weibo-upload image': ['Sohu'],
    'Sohu Weibo-posting': ['Sohu'],
    'Sohu-video': ['Sohu'],
    'Solidfiles': ['SolidFiles'],
    'SonyTV': ['SonyLIV'],
    'Soonr-download': ['Soonr'],
    'Soonr-upload': ['Soonr'],
    'Sopcast': ['SopCast'],
    'SoulSeek': ['Soulseek'],
    'SoundCloud': ['SoundCloud'],
    'SoundCloud-download': ['SoundCloud'],
    'SoundCloud-upload': ['SoundCloud'],
    'SourceForge': ['SourceForge'],
    'SouthWest': ['Southwest'],
    'Speedtest.net': ['Speedtest.net'],
    'SpiderOak': ['SpiderOak'],
    'Spiegel': ['Spiegel'],
    'Splashtop Remote': ['Splashtop'],
    'Splunk': ['Splunk'],
    'Spotify': ['Spotify'],
    'SSDP': ['SSDP'],
    'SSH': ['SSH'],
    'SSH Protocol': ['SSH'],
    'SSL': ['SSL/TLS'],
    'SSL Protocol': ['SSL/TLS'],
    'StarCraft II': ['StarCraft II'],
    'Stealthy': ['Stealthy'],
    'Steam': ['Steam'],
    'Steam_Game': ['Steam'],
    'Steam_Streaming': ['Steam'],
    'Stitch': ['Stitch'],
    'Stitcher': ['Stitcher Radio'],
    'StockStar': ['STOCKSTAR'],
    'Stocktwits': ['Stocktwits'],
    'Stratum mining protocol': ['Stratum'],
    'STUN': ['STUN'],
    'SugarCRM': ['SugarCRM'],
    'Sumologic': ['Sumo Logic'],
    'SuperVPM': ['SuperVPM'],
    'Supremo': ['Supremo Remote Desktop'],
    'Surfshark': ['Surfshark VPN'],
    'Surveymonkey': ['SurveyMonkey'],
    'SVT Play': ['SVT'],
    'Sybase-SQL Anywhere': ['Sybase'],
    'Symantec-update': ['Symantec Update'],
    'SymantecLiveUpdate': ['Symantec Update'],
    'Sync': ['Sync'],
    'Synergy2': ['Synergy'],
    'Syslog': ['Syslog'],
    'Syslog Protocol': ['Syslog'],
    'Swapper': ['The Swapper'],
    'TACACS+': ['TACACS+'],
    'TACACS Protocol': ['TACACS+'],
    'Tagged': ['Tagged'],
    'Tales Runner': ['Tales Runner'],
    'Tango': ['Tango'],
    'TeamSpeak': ['TeamSpeak'],
    'TeamSpeak2': ['TeamSpeak'],
    'TeamViewer': ['TeamViewer'],
    'TeamViewer-web-Join Meeting': ['TeamViewer'],
    'TeamViewer-web-Management Console': ['TeamViewer'],
    'Teamwork': ['Teamwork'],
    'TED': ['TED Talks', 'TED Talks CDN'],
    'Telegram': ['Telegram for Web'],
    'Telegram-call': ['Telegram for Web'],
    'Telnet': ['Telnet'],
    'Telnet Protocol': ['Telnet'],
    'TencentNews': ['Tencent'],
    'Teredo Protocol': ['Teredo'],
    'Thunder': ['ThunderVPN / SecureVPN'],
    'TikTok': ['TikTok'],
    'TNS Protocol': ['TNS'],
    'Tor': ['Tor'],
    'TOR': ['Tor'],
    'TouchVPN': ['TouchVPN'],
    'Torrent Swapper': ['BitTorrent', 'BitTorrent announce', 'BitTorrent Scrape'],
    'Torrent Monster': ['BitTorrent', 'BitTorrent announce', 'BitTorrent Scrape'],
    'TransferBigFiles': ['TransferBigFiles'],
    'TrendMicro': ['TrendMicro Update', 'Trend Micro Earthagent', 'Trend Micro Apex One'],
    'TrillianAstra': ['Trillian'],
    'Trillian_FileTransfer': ['Trillian'],
    'Tube8': ['Tube8'],
    'Tumblr': ['Tumblr'],
    'Tumblr_Posting': ['Tumblr'],
    'TunnelBear': ['TunnelBear'],
    'Turbo VPN': ['Turbo VPN'],
    'Turbo Torrent': ['BitTorrent'],
    'TvAnts': ['Tvants'],
    'TVB': ['TVB'],
    'Twitch.tv-video play': ['Twitch'],
    'Twitch.tv-video access': ['Twitch'],
    'Twitter': ['Twitter'],
    'Twitter Clients': ['Twitter', 'Twitter Media'],
    'Twitter Media': ['Twitter Media'],
    'Twitter Social Plugins': ['Twitter', 'Twitter Media'],
    'Twitter_Replies': ['Twitter'],
    'Twoo': ['Twoo'],
    'Uber': ['Uber'],
    'UberConference': ['UberConference'],
    'UltraSurf': ['UltraSurf VPN extension'],
    'Ultrasurf Chrome extension': ['UltraSurf VPN extension'],
    'Ultraviewer': ['Ultraviewer'],
    'Unlimited VPN': ['VPN Unlimited'],
    'Upload.info': ['Upload.in'],
    'Urban Dictionary': ['Urban Dictionary'],
    'UsaToday': ['USA TODAY'],
    'Userlike': ['Userlike'],
    'Vagaa': ['Vagaa TCP', 'Vagaa UDP'],
    'VANCL': ['VANCL'],
    'vBulletin': ['vBulletin'],
    'Vbulletin_Posting': ['vBulletin'],
    'Vdisk.me': ['vDisk'],
    'Ventrilo': ['Ventrilo'],
    'Vevo': ['VEVO'],
    'Viber': ['Viber'],
    'Viber_IM': ['Viber'],
    'Viber_VoIP': ['Viber'],
    'Viber-file-transfer': ['Viber Upload'],
    'Vidyo': ['Vidyo'],
    'Vimeo': ['Vimeo'],
    'ViPNet VPN': ['VipNet Client 4.5'],
    'Vision Helpdesk': ['Vision Helpdesk'],
    'VisionProject': ['VisionProject'],
    'VivaNews': ['VIVA'],
    'VK': ['VK'],
    'Vkontakte': ['VK'],
    'Vkontakte-chat': ['VK'],
    'Vkontakte-messaging': ['VK'],
    'Vkontakte-posting': ['VK'],
    'Vkontakte-multimedia': ['VK Media'],
    'VNC': ['VNC'],
    'Voddler': ['Voddler'],
    'Vox': ['Vox Media'],
    'VPN 360 and Unlimited VPN': ['VPN 360'],
    'VSee': ['VSee'],
    'Vuze': ['Vuse'],
    'Vuze_IM': ['Vuse'],
    'Vuze_P2P': ['Vuze'],
    'VZOchat': ['VZOChat'],
    'WAP': ['WAP'],
    'Warez': ['Warez P2P Client'],
    'WashingTonPost': ['Washington Post'],
    'Waysonline': ['WaysOnline'],
    "Web Browser": ['FreeMyBrowser', 'Yandex Browser telemetry', 'Firefox telemetry'],
    'WEB.DE-mail': ['Web.de'],
    'WebDAV': ['WebDav'],
    'WebDAV Protocol': ['WebDav'],
    'WebEX': ['WebEx'],
    'WebEx Webinars and Online Events': ['WebEx'],
    'Web_Fetion': ['Fetion'],
    'WebSocket Protocol': ['Websocket'],
    'WeChat': ['WeChat'],
    'WeChat-file transfer': ['WeChat'],
    'WeChat-audio video chat': ['WeChat'],
    'Weico': ['Weico iPhone'],
    'Weiyun': ['Weiyun'],
    'WeTransfer': ['WeTransfer'],
    'WeTransfer-download': ['WeTransfer'],
    'WeTransfer-upload': ['WeTransfer'],
    'WhatsApp': ['WhatsApp'],
    'WhatsApp Messenger': ['WhatsApp', 'WhatsApp Chat', 'WhatsApp Media'],
    'WhatsApp Messenger-file transfer': ['WhatsApp Media'],
    'WhatsApp Messenger-voice call': ['WhatsApp'],
    'WhatsApp Messenger-web/PC': ['WhatsApp', 'WhatsApp Chat', 'WhatsApp Media'],
    'When I Work': ['When I Work'],
    'Whois': ['Whois'],
    'Wickr': ['Wickr'],
    'Wiley': ['Wiley'],
    'Windscribe': ['Windscribe'],
    'Windows Azure Cloud Services': ['Microsoft Azure'],
    'WindowsUpdate': ['WinUpdate', 'Microsoft Update'],
    'Windows Update': ['WinUpdate', 'Microsoft Update'],
    'WindowsUpdate': ['WinUpdate', 'Microsoft Update'],
    'Windows Server Update Service (WSUS)': ['WinUpdate', 'Microsoft Update'],
    'Windows Remote Management - WinRm': ['PSRemoting (WinRM)'],
    'Wire': ['Wire'],
    'Wireguard Tunnel Protocol': ['Wireguard Protocol'],
    'Wix.com': ['Wix'],
    'Wolfenstein-Enemy Territory': ['Wolfenstein'],
    'Wonderfile': ['WonderFile'],
    'WordPress': ['WordPress'],
    'World Of Tanks': ['World of Tanks'],
    'Wuala': ['Wuala'],
    'Xbox Live': ['Xbox Live'],
    'Xchat': ['Xchat'],
    'Xero': ['Xero'],
    'Xunlei': ['Xunlei'],
    'Xware-xTRM': ['Xware xTrm'],
    'Yahoo! Messenger': ['Yahoo Messenger'],
    'Yahoo! Messenger-upload': ['Yahoo file transfer'],
    'YahooMsg_IM': ['Yahoo Messenger', 'Yahoo IM Proxy', 'Yahoo MSG'],
    'YahooMsg_Transfer': ['Yahoo file transfer'],
    'Yahoo_Video': ['Yahoo Webcam'],
    'YahooMsg_VoIP': ['Yahoo Messenger', 'Yahoo IM Proxy', 'Yahoo MSG', 'Yahoo Voice', 'Yahoo Webcam'],
    'Yandex': ['Yandex Browser', 'Yandex Mail', 'Yandex Maps', 'Yandex Market', 'Yandex Messenger',
               'Yandex Music', 'YandexEfir', 'Yandex Taxi', 'Yandex telemost', 'Yandex telemost call',
               'Yandex Translate', 'Yandex.Disk', 'Yandex.Disk download', 'Yandex.Disk upload', 'Yandex.Money'],
    'Yandex Browser': ['Yandex Browser'],
    'Yandex-disk': ['Yandex.Disk'],
    'Yandex-disk-download': ['Yandex.Disk download'],
    'Yandex-disk-upload': ['Yandex.Disk upload'],
    'Yandex_IM': ['Yandex Messenger'],
    'Yandex Mail': ['Yandex Mail'],
    'Yandex_Mail': ['Yandex Mail'],
    'Yandex-maps': ['Yandex Maps'],
    'Yandex-multimedia': ['Yandex Music', 'YandexEfir'],
    'Yelp': ['Yelp'],
    'Yoics': ['Yoics'],
    'Yosemite Server Backup': ['Yosemite Backup'],
    'Your Freedom': ['Your Freedom VPN'],
    'YourFreedom': ['Your Freedom VPN'],
    'YouTube': ['YouTube'],
    'Youtube': ['YouTube'],
    'YouTube-upload': ['YouTube Upload'],
    'YouTube_Downloader': ['YouTube Upload'],
    'Yuuguu': ['Yuuguu'],
    'YY Voice': ['YY Voice'],
    'YY_IM': ['YY Voice'],
    'Zabbix': ['Zabbix'],
    'Zadarma': ['Zadarma Conf'],
    'Zadarma Conf': ['Zadarma Conf'],
    'zalil': ['zalil'],
    'Zapier': ['Zapier'],
    'ZARA': ['ZARA'],
    'Zefiro': ['Zefiro'],
    'Zello': ['Zello'],
    'Zendesk': ['Zendesk'],
    'Zenefits': ['Zenefits'],
    'ZenMate': ['ZenMate Browser Extension'],
    'ZenVPN': ['ZenVPN'],
    'ZeroTier': ['ZeroTier'],
    'ZeroTier One': ['ZeroTier'],
    'zFile': ['zFile'],
    'Zillow': ['Zillow'],
    'ZIOP': ['ZIOP'],
    'Zippyshare': ['Zippyshare'],
    'zippyshare': ['Zippyshare'],
    'Zipza': ['Zipza'],
    'ZMTP': ['ZMTP'],
    'Zona': ['Zona'],
    'Zoom': ['Zoom'],
    'Zoom-chat': ['Zoom chat'],
    'ZoomFoot_Download': ['Zoom file sharing'],
    'Zoom-file transfer': ['Zoom file sharing'],
    'Zotero': ['Zotero'],
    'Zougla': ['Zougla'],
    'Zovine Messenger': ['Zovine Messenger'],
    'Zovine_Messenger': ['Zovine Messenger'],
    'Zulipchat': ['Zulipchat'],
    'ZxShell': ['ZxShell'],
    f'{chr(956)}Torrent': [f'{chr(956)}Torrent'],
}

appgroup_compliance = {
    'Microsoft Services': ['Microsoft and Office365 Services'],
}

l7_category_compliance = {
    'Apt-get': ['Software update'],
    'BT': ['File sharing P2P'],
    'DNF': ['Software update'],
    'Proprietary Tunneling Tools': ['Tunneling'],
}

url_category_compliance = {
    'Anonymizer/proxy avoidance sites': ['Anonymizers'],
}

new_applicationgroup = [
    {   "name": "Cloud Services",
        "app_list": [
            "Bearlo Cloud",
            "CloudCall",
            "Cloudinary",
            "CloudTrax",
            "Fastly Cloud",
            "Filecloud.me",
            "FutureNetCloud",
            "GetFileCloud",
            "Jottacloud",
            "Mail.ru Cloud",
            "pCloud",
            "SoundCloud",
            "VideoMost Cloud",
        ]
    },
    {
        "name": "Download Manager",
        "app_list": [
            "Internet Download Manager",
            "OnlyOffice Download File",
            "BitTorrent",
            "BitTorrent announce",
            "BitTorrent Scrape",
            "Nyaa Torrents",
            f"{chr(956)}Torrent",
            "GetSpace",
            "MediaGet",
            "FlashGet DNS",
            "FlashGet HTTP",
            "FlashGet TCP",
            "FlashGet UDP",
        ]
    },
    {
        "name": "File Upload",
        "app_list": [
            "Amazon Chime upload/download",
            "Dropbox Web Upload",
            "Facebook Upload",
            "OnlyOffice Upload File",
            "Proton Drive upload/download",
            "Upload.in",
            "UploadFile",
            "Viber Upload",
            "Webinar uploading",
            "Yandex.Disk upload",
            "YouTube Upload",
        ]
    },
    {
        "name": "Media Sharing",
        "app_list": [
            "Amazon Chime upload/download",
            "Dropbox Web Download",
            "Dropbox Web Upload",
            "Facebook Upload",
            "Internet Download Manager",
            "OnlyOffice Download File",
            "OnlyOffice Upload File",
            "Proton Drive upload/download",
            "Upload.in",
            "UploadFile",
            "Viber Upload",
            "Webinar uploading",
            "Yandex.Disk download",
            "Yandex.Disk upload",
            "YouTube Upload",
        ]
    },
    {
        "name": "Microsoft and Office365 Services",
        "app_list": [
            "Groove",
            "Live Meeting",
            "Live Mesh",
            "Microsoft Azure",
            "Microsoft Defender",
            "Microsoft Delivery optimization",
            "Microsoft Exchange",
            "Microsoft location services",
            "Microsoft login",
            "Microsoft maps",
            "Microsoft Outlook Mobile",
            "Microsoft SCOM",
            "Microsoft Store",
            "Microsoft telemetry",
            "Microsoft Update",
            "Microsoft Whiteboard",
            "MS MMS",
            "MS Teams",
            "MS Teams File sharing & Chat",
            "MSN",
            "NSPlayer",
            "Office365",
            "OneDrive",
            "Outlook",
            "SharePoint",
            "Skype",
            "Skype Call",
            "Skype Chat",
            "Skype for Business",
            "Skype for business desktop sharing",
            "Skype for business File Transfer",
            "Skype screen sharing",
            "Visual Studio",
            "WinUpdate",
            "WMV",
        ]
    },
    {
        "name": "Instant Chat",
        "app_list": [
            "1C-Connect chat",
            "Amazon Chime chat",
            "Blackboard Chat",
            "Chatango",
            "ChatWork desktop",
            "ChatWork web",
            "Facebook  Chat",
            "Digsby Beta",
            "Google Chat",
            "eBuddy",
            "eBuddy for Android",
            "Hipchat",
            "Hotline",
            "Hyves chat",
            "ICE Chat",
            "iChat",
            "IRC chat",
            "KakaoTalk chat",
            "Linkchat",
            "MS Teams File sharing & Chat",
            "MySpaceIM",
            "Paltalk",
            "Pichat",
            "Rocket.Chat",
            "Rocket.Chat Files",
            "Rocket.Chat Messages",
            "Skype Chat",
            "Snapchat",
            "Talk-me",
            "Qnext",
            "VZOChat",
            "WeChat",
            "WhatsApp Chat",
            "Xchat",
            "xntalk",
            "Zoom chat",
            "Zulipchat",
        ]
    }
]
